### ISSUE TITLE
Implement TotalFilCircSupply correctly

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#4012] opened 2020-04-22 18:45 UTC
### Description

The VM context is supposed to supply `TotalFilCircSupply` for actor computations. It's not currently clear what this is. We need to learn how to acquire this value and reimplement the method.

### Acceptance criteria

1. TotalFilCircSupply supplies the right value.

**Comment by anorth** [comment] 2020-04-22 20:19
Duplicate of #3996

**Closed by anorth** 2020-04-22 20:19 UTC
