### ISSUE TITLE
[bug]FILECOIN_USE_PRECOMPILED_RUST_PROOFS=true go run ./build deps pkg-config --version 0.27.1 Installing dependencies... go get -u github.com/whyrusleeping/gx package golang.org/x/crypto/ed25519: golang.org/x/crypto is a custom import path for https://go.googlesource.com/crypto, but /usr/local/go/gopath/src/golang.org/x/crypto is checked out from https://github.com/golang/crypto.git package golang.org/x/crypto/blake2s: golang.org/x/crypto is a custom import path for https://go.googlesource.com/crypto, but /usr/local/go/gopath/src/golang.org/x/crypto is checked out from https://github.com/golang/crypto.git package golang.org/x/crypto/sha3: golang.org/x/crypto is a custom import path for https://go.googlesource.com/crypto, but /usr/local/go/gopath/src/golang.org/x/crypto is checked out from https://github.com/golang/crypto.git Command 'go get -u github.com/whyrusleeping/gx' failed: exit status 1 exit status 1

### ISSUE THREAD

**Issue by block2020** [filecoin-project/go-filecoin#2448] opened 2019-03-29 04:52 UTC
**Describe the bug**

**To Reproduce**
2. Run this command '...'
3. See error

**Expected behavior**

**Screenshots**
If applicable, add logging output or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - Browser [if applicable, e.g. chrome, safari]

**Additional context**

**Comment by frrist** [comment] 2019-03-29 16:42
duplicate of #2447

**Closed by frrist** 2019-03-29 16:42 UTC
Labels: C-bug
