### ISSUE TITLE
[bug] go-filecoin crashed when i  propose many storage deals at one time

### ISSUE THREAD

**Issue by ipfsmainofficial** [filecoin-project/go-filecoin#2673] opened 2019-04-28 08:36 UTC
when i propose many deals to my miner at one time(use go-filecoin client propose-storage-deal), the miner crashed.
log here:
```
Apr 17 16:42:45.318 INFO encoding, layer {}: 0, place: storage-proofs/src/layered_drgporep.rs:440 storage_proofs::layered_drgporep, root: storage-proofs
fatal error: concurrent map read and map write

goroutine 44166 [running]:
runtime.throw(0x14a394d, 0x21)
        /usr/local/go/src/runtime/panic.go:617 +0x72 fp=0xc08e301980 sp=0xc08e301950 pc=0x4e04d2
runtime.mapaccess2(0x134b300, 0xc098d80cc0, 0xc04ff6eb80, 0xc04ff6eb80, 0x5)
        /usr/local/go/src/runtime/map.go:472 +0x284 fp=0xc08e3019c8 sp=0xc08e301980 pc=0x4c07a4
reflect.mapaccess(0x134b300, 0xc098d80cc0, 0xc04ff6eb80, 0x14972f0)
        /usr/local/go/src/runtime/map.go:1321 +0x3f fp=0xc08e301a00 sp=0xc08e3019c8 pc=0x4c29ff
reflect.Value.MapIndex(0x134b300, 0xc098d80d58, 0x195, 0x1302c20, 0xc04ff6eb80, 0x8b, 0x12eb520, 0xc03ebdb640, 0x97)
        /usr/local/go/src/reflect/value.go:1112 +0x10a fp=0xc08e301a60 sp=0xc08e301a00 pc=0x56c8ea
encoding/json.mapEncoder.encode(0xc06ec1b4d0, 0xc051df84d0, 0x134b300, 0xc098d80d58, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:702 +0x303 fp=0xc08e301ba8 sp=0xc08e301a60 pc=0x5b8963
encoding/json.mapEncoder.encode-fm(0xc051df84d0, 0x134b300, 0xc098d80d58, 0x195, 0x100)
        /usr/local/go/src/encoding/json/encode.go:678 +0x64 fp=0xc08e301be8 sp=0xc08e301ba8 pc=0x5c45a4
encoding/json.structEncoder.encode(0xc054792d80, 0x3, 0x4, 0xc051df84d0, 0x1418ba0, 0xc098d80d50, 0x199, 0x5b0100)
        /usr/local/go/src/encoding/json/encode.go:660 +0x304 fp=0xc08e301c88 sp=0xc08e301be8 pc=0x5b8434
encoding/json.structEncoder.encode-fm(0xc051df84d0, 0x1418ba0, 0xc098d80d50, 0x199, 0xc098d80100)
        /usr/local/go/src/encoding/json/encode.go:631 +0x76 fp=0xc08e301cd8 sp=0xc08e301c88 pc=0x5c4526
encoding/json.ptrEncoder.encode(0xc03c07bd00, 0xc051df84d0, 0x13808c0, 0xc098d80d50, 0x16, 0x1380100)
        /usr/local/go/src/encoding/json/encode.go:806 +0xb2 fp=0xc08e301d20 sp=0xc08e301cd8 pc=0x5b98b2
encoding/json.ptrEncoder.encode-fm(0xc051df84d0, 0x13808c0, 0xc098d80d50, 0x16, 0xc08e300100)
        /usr/local/go/src/encoding/json/encode.go:801 +0x64 fp=0xc08e301d60 sp=0xc08e301d20 pc=0x5c4724
encoding/json.(*encodeState).reflectValue(0xc051df84d0, 0x13808c0, 0xc098d80d50, 0x16, 0x13a0100)
        /usr/local/go/src/encoding/json/encode.go:334 +0x82 fp=0xc08e301d98 sp=0xc08e301d60 pc=0x5b5c02
encoding/json.(*encodeState).marshal(0xc051df84d0, 0x13808c0, 0xc098d80d50, 0xc098d80100, 0x0, 0x0)
        /usr/local/go/src/encoding/json/encode.go:306 +0xee fp=0xc08e301de0 sp=0xc08e301d98 pc=0x5b56ae
encoding/json.Marshal(0x13808c0, 0xc098d80d50, 0x2cd5, 0xc09a070020, 0x0, 0x2, 0x16eb700)
        /usr/local/go/src/encoding/json/encode.go:160 +0x52 fp=0xc08e301e58 sp=0xc08e301de0 pc=0x5b4cd2
github.com/filecoin-project/go-filecoin/protocol/storage.(*Miner).saveDealsAwaitingSeal(0xc0962aa380, 0x2cd5, 0xc003f5c240)
        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/protocol/storage/miner.go:502 +0x3f fp=0xc08e301ed0 sp=0xc08e301e58 pc=0xcbc2af
github.com/filecoin-project/go-filecoin/protocol/storage.(*Miner).processStorageDeal(0xc0962aa380, 0xc003f5c240, 0x26)
        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/protocol/storage/miner.go:460 +0x80e fp=0xc08e301fc8 sp=0xc08e301ed0 pc=0xcbbe0e
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1337 +0x1 fp=0xc08e301fd0 sp=0xc08e301fc8 pc=0x50fa71
created by github.com/filecoin-project/go-filecoin/protocol/storage.acceptProposal
        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/protocol/storage/miner.go:342 +0x213

goroutine 1 [chan receive, 1 minutes]:
github.com/filecoin-project/go-filecoin/commands.runAPIAndWait(0x16fbdc0, 0xc000314300, 0xc00000c1e0, 0xc00031a1e0, 0xc000302230, 0x0, 0x0)
        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:184 +0x57a
github.com/filecoin-project/go-filecoin/commands.daemonRun(0xc000302230, 0x16fca40, 0xc0002fe420, 0x16e4b80, 0xc0002efaa0, 0x1372b00, 0xc0002fe4d8)
        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:117 +0x7bc
github.com/filecoin-project/go-filecoin/commands.glob..func40(0xc000302230, 0x16fca40, 0xc0002fe420, 0x16e4b80, 0xc0002efaa0, 0x16e5e40, 0x22f2d80)

        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:117 +0x7bc
github.com/filecoin-project/go-filecoin/commands.glob..func40(0xc000302230, 0x16fca40, 0xc0002fe420, 0x16e4b80, 0xc0002efaa0, 0x16e5e40, 0x22f2d80)
        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/commands/daemon.go:43 +0x53
gx/ipfs/Qmf46mr235gtyxizkKUkTH5fo62Thza2zwXR4DWC7rkoqF/go-ipfs-cmds.(*executor).Execute(0xc0002ec268, 0xc000302230, 0x16fca40, 0xc0002fe420, 0x16e4b80, 0xc0002efaa0, 0xc0001a9d18, 0x4bca75)
        /home/murphy/go/src/gx/ipfs/Qmf46mr235gtyxizkKUkTH5fo62Thza2zwXR4DWC7rkoqF/go-ipfs-cmds/executor.go:81 +0x171
github.com/filecoin-project/go-filecoin/commands.(*executor).Execute(0xc0002f2b60, 0xc000302230, 0x16fca40, 0xc0002fe420, 0x16e4b80, 0xc0002efaa0, 0xc0002fe420, 0x0)
        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/commands/main.go:212 +0x3a2
gx/ipfs/Qmf46mr235gtyxizkKUkTH5fo62Thza2zwXR4DWC7rkoqF/go-ipfs-cmds/cli.Run(0x16fbe00, 0xc000182020, 0x2207400, 0xc000188040, 0x4, 0x4, 0xc000184000, 0xc000184008, 0xc000184010, 0x15ee360, ...)
        /home/murphy/go/src/gx/ipfs/Qmf46mr235gtyxizkKUkTH5fo62Thza2zwXR4DWC7rkoqF/go-ipfs-cmds/cli/run.go:138 +0xa63
github.com/filecoin-project/go-filecoin/commands.Run(0xc000188040, 0x4, 0x4, 0xc000184000, 0xc000184008, 0xc000184010, 0x0, 0x0, 0xd00ac7)
        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/commands/main.go:191 +0xad
main.main()
        /home/murphy/go/src/github.com/filecoin-project/go-filecoin/main.go:46 +0x2ff
```

**Comment by ipfsmainofficial** [comment] 2019-04-28 08:38
I have fixed this bug use a lock.

**Comment by frrist** [comment] 2019-04-29 16:34
Hi @ipfsmainofficial, can you please share the version of the binary you are running? This is was a known bug that has been fixed in master and will be deployed on our next release.

 Since it appears you are connected to the devnet that would mean you are running `test-devnet-0.1.4` -- I am going to close this as it has been fixed.

flagging a a duplicate of https://github.com/filecoin-project/go-filecoin/issues/2645

**Closed by frrist** 2019-04-29 16:34 UTC
Labels: C-bug
