### ISSUE TITLE
Test timeout after plumbing mthdsig/ntwk/ps

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2078] opened 2019-02-22 17:57 UTC
We have been seeing a timeout failure in our tests recently. They all timeout at the same time. Please add any additional failures that look similar to this list so we can help track down when it first occurred.

```
PASS
ok  	github.com/filecoin-project/go-filecoin/plumbing/mthdsig	0.050s
?   	github.com/filecoin-project/go-filecoin/plumbing/ntwk	[no test files]
?   	github.com/filecoin-project/go-filecoin/plumbing/ps	[no test files]
Too long with no output (exceeded 10m0s)
```

- https://circleci.com/gh/filecoin-project/go-filecoin/11369?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
- https://circleci.com/gh/filecoin-project/go-filecoin/11377?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by travisperson** [comment] 2019-02-22 18:01
This appears to be the first time it in master

- https://circleci.com/gh/filecoin-project/go-filecoin/11307

**Comment by travisperson** [comment] 2019-02-22 18:06
Might be related to: https://github.com/filecoin-project/go-filecoin/pull/1954 seems to be the PR when it started.

**Comment by rosalinekarr** [comment] 2019-02-22 18:58
@travisperson I think this is a duplicate of #2059. I'm closing in favor of that issue.

**Closed by rosalinekarr** 2019-02-22 18:58 UTC
Labels: C-transient-test-failure
