### ISSUE TITLE
Check for dependencies prior to build

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#2531] opened 2019-04-09 19:16 UTC
### Description

A common source of problems for a lot users comes from not having dependencies installed, or having the wrong version.

I think we can provide some better checking of dependencies. At minimum the existed, and even better would be to provide version checking.

I've also updated the bug report template (#2512) to include a lot more information from our users. I think we should automatically generate this when a build fails and provide the exact information we want the user to provide. The easier we make it the more likely we will get the information we need.

**Comment by anorth** [comment] 2019-04-10 00:22
I think this is a duplicate of #1963. @travisperson please close if you agree and migrate any extra information there.

**Comment by anorth** [comment] 2019-04-12 01:59
Closing as a duplicate, please re-open if I'm wrong.

**Closed by anorth** 2019-04-12 01:59 UTC
Labels: A-build
