### ISSUE TITLE
Cannot sync chain on user devnet (regression)

### ISSUE THREAD

**Issue by jimpick** [filecoin-project/go-filecoin#2155] opened 2019-03-02 19:29 UTC
I upgraded the two nodes I was running on the user devnet to master yesterday, and they both stopped syncing the chain.

I tried reseting the one I am running on Linux (delete ~/.filecoin, etc.), and even after an hour, it wouldn't sync the chain past a height of zero.

I reverted to code from Tuesday, rebuilt, and confirmed that the chain would sync with the older code.

Then I ran `git bisect` and tried a bunch of different builds, and determined that the chain stopped syncing once this commit was added:

https://github.com/filecoin-project/go-filecoin/commit/b2c75bd799e058f6a382c252d0dba3f425e35b5f

It takes a while to test, and it's possible I'm just seeing randomness, but it feels like it's fairly reproducible.

I'd recommend that somebody try to confirm these results - if true, that means that nobody has been able to successfully try out the user devnet since about Wednesday (the instructions on the wiki instruct building from source on master).

**Comment by rkowalick** [comment] 2019-03-04 18:09
@jimpick,

Looking into reproducing this right now.

**Comment by phritz** [comment] 2019-03-04 19:21
@rkowalick isn't thi wai? there is no expectation that you can interact with the user devent with code built from any other commit than the one the user devnet was cut from. in this case there is the breaking commit mentioned that will prevent interoperability.

**Comment by jimpick** [comment] 2019-03-04 19:58
I just did a Zoom screenshare with @rkowalick and we compared our setups ... his seems to sync OK, and mine definitely is acting strange.

I'm going to try to reproduce on OS X.

**Comment by jimpick** [comment] 2019-03-04 20:03
It's working on my iMac, but not on Ubuntu.

**Comment by jimpick** [comment] 2019-03-05 07:25
I discovered that `go-filecoin swarm peers` wasn't listing any peers outside of the bootstrap servers ... the wireless connection to my Ubuntu machine was very, very weak. I went out and bought an updated mesh router, and now the Linux machine is acting consistent with the OS X machine. So bad networking on my network was definitely part of the problem.

There appears to be an additional problem now ... once the chain syncs, the head doesn't move forward - it will continually loop with the following output:

```
23:18:16.527  INFO chain.sync: syncing the chain, currently at block height 34670 default_syncer.go:153
23:18:16.609  INFO chain.sync: syncing the chain, currently at block height 33576 default_syncer.go:153
23:18:16.670  INFO chain.sync: syncing the chain, currently at block height 32526 default_syncer.go:153
23:18:16.732  INFO chain.sync: syncing the chain, currently at block height 31440 default_syncer.go:153
23:18:16.787  INFO chain.sync: syncing the chain, currently at block height 30367 default_syncer.go:153
23:18:16.838  INFO chain.sync: syncing the chain, currently at block height 29371 default_syncer.go:153
23:18:16.890  INFO chain.sync: syncing the chain, currently at block height 28419 default_syncer.go:153
23:18:16.929  INFO chain.sync: syncing the chain, currently at block height 27537 default_syncer.go:153
23:18:16.990  INFO chain.sync: syncing the chain, currently at block height 26549 default_syncer.go:153
23:18:17.038  INFO chain.sync: syncing the chain, currently at block height 25550 default_syncer.go:153
23:18:17.081  INFO chain.sync: syncing the chain, currently at block height 24582 default_syncer.go:153
23:18:17.142  INFO chain.sync: syncing the chain, currently at block height 23394 default_syncer.go:153
23:18:17.187  INFO chain.sync: syncing the chain, currently at block height 22016 default_syncer.go:153
23:18:17.247  INFO chain.sync: syncing the chain, currently at block height 20900 default_syncer.go:153
23:18:17.308  INFO chain.sync: syncing the chain, currently at block height 19743 default_syncer.go:153
23:18:17.381  INFO chain.sync: syncing the chain, currently at block height 18668 default_syncer.go:153
23:18:17.460  INFO chain.sync: syncing the chain, currently at block height 17617 default_syncer.go:153
23:18:17.536  INFO chain.sync: syncing the chain, currently at block height 16553 default_syncer.go:153
23:18:17.572  INFO chain.sync: syncing the chain, currently at block height 15558 default_syncer.go:153
23:18:17.614  INFO chain.sync: syncing the chain, currently at block height 14354 default_syncer.go:153
23:18:17.657  INFO chain.sync: syncing the chain, currently at block height 12977 default_syncer.go:153
23:18:17.693  INFO chain.sync: syncing the chain, currently at block height 11878 default_syncer.go:153
23:18:17.731  INFO chain.sync: syncing the chain, currently at block height 10987 default_syncer.go:153
23:18:17.763  INFO chain.sync: syncing the chain, currently at block height 10156 default_syncer.go:153
23:18:17.798  INFO chain.sync: syncing the chain, currently at block height 9315 default_syncer.go:153
23:18:17.857  INFO chain.sync: syncing the chain, currently at block height 8443 default_syncer.go:153
23:18:17.891  INFO chain.sync: syncing the chain, currently at block height 7595 default_syncer.go:153
23:18:17.939  INFO chain.sync: syncing the chain, currently at block height 6757 default_syncer.go:153
23:18:17.978  INFO chain.sync: syncing the chain, currently at block height 5903 default_syncer.go:153
23:18:18.017  INFO chain.sync: syncing the chain, currently at block height 5124 default_syncer.go:153
23:18:18.059  INFO chain.sync: syncing the chain, currently at block height 4282 default_syncer.go:153
23:18:18.123  INFO chain.sync: syncing the chain, currently at block height 3471 default_syncer.go:153
23:18:18.164  INFO chain.sync: syncing the chain, currently at block height 2647 default_syncer.go:153
23:18:18.204  INFO chain.sync: syncing the chain, currently at block height 1830 default_syncer.go:153
23:18:18.248  INFO chain.sync: syncing the chain, currently at block height 1089 default_syncer.go:153
23:18:18.290  INFO chain.sync: syncing the chain, currently at block height 330 default_syncer.go:153
23:18:18.310  INFO chain.sync: chain synced default_syncer.go:158
23:18:18.311  INFO consensus.: [TIMER] DefaultProcessor.ApplyMessage CID: zDPWYqFCurathEpcdLfJjcZ4MniNzWSvdzeZt2ZdAqD6x4SYuxj5 - elapsed time: 0s processor.go:272
23:18:18.311  INFO consensus.: [TIMER] DefaultProcessor.ApplyMessage CID: zDPWYqFCsKnsWHK7X7GkvY6CZM2h95XCxyXW8XJLTjzvbutjWGyj - elapsed time: 0s processor.go:272
23:18:18.311  INFO consensus.: [TIMER] DefaultProcessor.ProcessBlock BlkCID: zDPWYqFD1R4povAi2A9DZHXVvXc4Cku1NsLEawFCN5yVGjiwnjY8 - elapsed time: 1ms processor.go:100
23:18:18.311  INFO       node: error handling blocks: { zDPWYqFD3udGUyZ6p2iVHDQooSrFWxZcYsXEL2twG5pyyXooYUus } node.go:485
```

I think this might be a different issue than what I originally reported here.

**Comment by phritz** [comment] 2019-03-05 17:15
this looks in progress, moving to in progress @rkowalick

**Comment by rkowalick** [comment] 2019-03-05 22:16
So these issues are being caused by not using the same code that is on the user devnet. We are currently not guaranteeing any sort of backwards compatibility between code changes, so the only reliable way to connect to the user devnet is to build from the same code that is running on user devnet:
```
git fetch origin devnet-user -f
git checkout devnet-user
```
I have updated the documentation to ensure users are getting the right code, and a feature will be added to go-filecoin to prevent users on future user devnets from being about to join a devnet with incompatible software.

Please reopen if you are still having issues.

**Closed by rkowalick** 2019-03-05 22:16 UTC
Labels: C-bug
