### ISSUE TITLE
[bug]random seal proof validation errors

### ISSUE THREAD

**Issue by merced** [filecoin-project/go-filecoin#2832] opened 2019-05-24 02:50 UTC
**Describe the bug**

While verify seal results, two types of random errors occur.
1, ApplyMessage failed: seal proof was invalid SignedMessage cid=[zDPWYqFD8YMuZNaRJ7CXfvreXujuD4Pj4rf2YCHaSFNWWz5W58PP], this error can be seen in both local node which generate the proof and other nodes.
2,  message signature differs error like below, this message can only been viewed in the mining node which generate the proof.
```
[0;37m10:04:40.032 [31mERROR [0;34m    mqueue: [0mQueued message SignedMessage cid=[zDPWYqFD5mZj3GP876uGD6zt8S5TB5QeuB3gmCyQEGoz4qJfMXkD]: {
  "meteredMessage": {
    "message": {
      "to": "t22weugrvqojfm3imgbx3i2jtvuaqcmtuy56euvoq",
      "from": "t15y2ciylrvhv3b3sqwhb6547stnx4ftq357gt5ty",
      "nonce": "120",
      "value": null,
      "method": "commitSector",
      "params": "hULqAlggjK3OPSfZR+GFCYJEvqJP4+blEsLZmSGp4GF0ns3DrQJYILITZcDIYXV591zOOTN5zoKDLGU7Oyw0w4i/KafJu9wnWCBWDs7YlQP0T8jaUEBAA3wBw6d0p99pwqF2DZmw1M0jcFkBgKMXiiLXHYT4x7zWDxJM7AA6U93/1O37qCjFQXA44ZMqDdEAiO0mBA3eoVcHilE3W6YvSmorzKDqQcDmju36orFmfS3zogU2XchZebbXrJLs2VtsmwEQoMEEQQmVhiMX6wtJdtQzfgQFyvgLijJXIPTn60ZNL9E/jdw9UnHBEyrrkxXJPFg5l7eCBRT+LL2iIbWMiYoRToDECAJ7XwpU8zL95YUCJHuBixsWDqTloMLBFNCkzAqwZhypjePbkc9OAK6JGLJFzcMaoE+loNRRbV5xYCGkdMc8Hh9ezXoL/ssLG2nlWvVf5V7lfIdLGc94zoUe+ksIz80Xcb4ekXkqyg2ePIO7BCPJdGt9PV9X4lnGtLyTWoyuKiGe3j0hzD/7YRUTLzdMI7txGGWM8Bf2pysffd2klOkrJUjpGt0n6IF2cAuzXT+qPQ8IBO6IjWWNg6okKA7wpd6Qb66xbedMs0V5UlzbjuNivcktyfOXP0jTf5SsM4Bca038xV19NNno2A=="
    },
    "gasPrice": "0.000000000000000001",
    "gasLimit": "300"
  },
  "signature": "6+OP9f30eeJ34wPlBz3gToDIoLBAzYIH7LFnQqdYwQsfNwaaX29n/hs3EkMqJ+EAeQNCOloD/UOGbtTErjfWkQA="
} differs from mined message SignedMessage cid=[zDPWYqFCxhPQdC5rffxM1vgL1LSqFMGwbqgwH2kx4QLAUmE7QaJA]: {
  "meteredMessage": {
    "message": {
      "to": "t22weugrvqojfm3imgbx3i2jtvuaqcmtuy56euvoq",
      "from": "t15y2ciylrvhv3b3sqwhb6547stnx4ftq357gt5ty",
      "nonce": "120",
      "value": null,
      "method": "commitSector",
      "params": "hULpAlggjK3OPSfZR+GFCYJEvqJP4+blEsLZmSGp4GF0ns3DrQJYIIWZnqnrvG+ud2j/K526HVbTgTO0pUrb4vVswjGzA0E9WCDkyKaVaVd0qRk4Og9gH3MqKiGDI54XqxZo4GQW4A+BblkBgJVTQPTe6bnIME7pJyeSDPpWKBLihHR0mP/5UnzslfUJPH7wAaQ1PPCMG0Je+iPTdpeD53ZBMYOJVd7PN7yfVSwzqjzJPJfPYBCWujbhcTrT6dOdWhy1ssR7tkijowDvgAeePF3KObGf0qxgOvXL3Vutm8RnBQXnZFytwWGbf49EO8TCeKOiQk7fN9ysOUYXi4rU7S6D2cOO7pgYnQNDC9fkfnO8S54Qx9u8aV2i46hpVR3Cb4C/e0pzLJBKeYJMoLQEQCa/5NMLZIqfTJbpYsMZng/NcoIGUzEr7q5hP1lZ1F5w5wuwQjp7ipnADugpZoHmqJBBGIxrMH8BFcETp3FXwpm1JZ3+vpNJkORwWH5kOrmf4uHpBsCo/6wPO+gHrwgll+UzRLEFn86GRQaVnBmhMyFcvA33PUsEsSWIfKQ6whHx6vqXyJfpaJ92RuASvrRDSOEhLXDfE0Oapk61Abrq34kIugpPr5DRuISu+0YJBwJByax0V5mUfeqC8ZAm0Q=="
    },
    "gasPrice": "0.000000000000000001",
    "gasLimit": "300"
  },
  "signature": "Kx6vlQsPJZhZH01Oj9PDF0aVZd/7X6gtl58Di88s+wx3IKABCSFp+vgKbPHB8I9Hw/Ew6bIzYz8zmzkJaq12CQA="
} with same sender & nonce [0;37mpolicy.go:66[0m
```

**To Reproduce**

**Expected behavior**

We should see consistent success verification results if keeps the replication and verification routine as is.
**Screenshots**

**Diagnostic information**

- Filecoin Inspect Ouput: 
- Current Head: 
- Connected Peers: 

**Version information**

- Go:  go version go1.12.4 linux/amd64
- Rust: rustc 1.33.0 (2aa4c46cf 2019-02-28)
- Cargo: cargo 1.33.0 (f099fe94b 2019-02-12)
- Commit:  16b615de0feb13e09b4173958cc9cf993a5b053f (master branch on 6/20)
- Go Env: 
- CC: 

**Additional context**

This error was observed in the private filecoin net by compile master branch of 6/20. No rust verification or seal routine has been modified.

**Comment by travisperson** [comment] 2019-05-24 16:55
I assume because this was a private network, can you tell us more about what you were doing on the network that resulted in this error?

**Comment by merced** [comment] 2019-05-25 01:21
The private net was constructed as the instruction of [#2294](https://github.com/filecoin-project/go-filecoin/issues/2294), followed by the standard procedure: get fund from faucet -> create miner -> create ask -> propose deal. as far as I can see, seal was successful all the time but there is probability that verify commit sector message could be failed due to above two failures, given that no code change.

**Comment by anorth** [comment] 2019-05-27 23:29
cc @laser

**Comment by laser** [comment] 2019-06-04 15:35
@anorth - I have not been able to reproduce this issue. I suggest that we close this issue. I suggest that we reopen this issue if some other user (or one of our team's developers) reproduces the issue which @merced has reported.

**Closed** 2019-06-05 01:47 UTC
Labels: C-bug
