### ISSUE TITLE
The miner waited too long to create the command

### ISSUE THREAD

**Issue by grandhelmsman** [filecoin-project/go-filecoin#2825] opened 2019-05-23 02:06 UTC
hello
`go-filecoin miner create 10 100 --gas-price=0.001 --gas-limit=300 --peerid `go-filecoin id | jq -r '.ID'`
Waiting, nearly 20 minutes,  
```
[root@localhost ~]# go-filecoin wallet balance t1wkgotukvy552n2q5gzesykowtjmrylbcp23y2yq
890
```

Try the command:
`go-filecoin miner set-price --from=t1xnehcdnb5kwt33rotzgdsoe5qm5ty6itf7kzo5q  --miner=t2ysgspglztifypffvfyvv2d6mswdruu37xtsf3da --gas-price=0.0001 --gas-limit=300 1 12880`   
Waiting, nearly 30 minutes,

**Comment by travisperson** [comment] 2019-05-24 17:23
@grandhelmsman could you please share the output of `go-filecoin inspect all`, this will help us debug this issue.

**Comment by grandhelmsman** [comment] 2019-05-27 03:58
[root@localhost ~]# go-filecoin inspect all
{"Config":{"api":{"accessControlAllowCredentials":false,"accessControlAllowMethods":["GET","POST","PUT"],"accessControlAllowOrigin":["http://localhost:8080","https://localhost:8080","http://127.0.0.1:8080","https://127.0.0.1:8080"],"address":"/ip4/127.0.0.1/tcp/13453"},"bootstrap":{"addresses":["/dns4/user.kittyhawk.wtf/tcp/9000/ipfs/Qmd6xrWYHsxivfakYRy6MszTpuAiEoFbgE1LWw4EvwBpp4","/dns4/user.kittyhawk.wtf/tcp/9001/ipfs/QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4","/dns4/user.kittyhawk.wtf/tcp/9002/ipfs/QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY","/dns4/user.kittyhawk.wtf/tcp/9003/ipfs/QmZGDLdQLUTi7uYTNavKwCd7SBc5KMfxzWxAyvqRQvwuiV","/dns4/user.kittyhawk.wtf/tcp/9004/ipfs/QmZRnwmCjyNHgeNDiyT8mXRtGhP6uSzgHtrozc42crmVbg"],"minPeerThreshold":1,"period":"10s"},"datastore":{"path":"badger","type":"badgerds"},"heartbeat":{"beatPeriod":"3s","beatTarget":"/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmcSFeiARE6DpFwsySFEVLw334HSBsqPFB3nTwkwEH2gED","nickname":"","reconnectPeriod":"10s"},"mining":{"autoSealIntervalSeconds":120,"minerAddress":"t25n5cxbphqoukk43fg5t3fqd6rrobxs7pnlht2zi","storagePrice":"0.02"},"mpool":{"maxNonceGap":"100","maxPoolSize":10000},"net":"devnet-user","observability":{"metrics":{"prometheusEnabled":false,"prometheusEndpoint":"/ip4/0.0.0.0/tcp/9400","reportInterval":"5s"},"tracing":{"jaegerEndpoint":"http://localhost:14268/api/traces","jaegerTracingEnabled":false,"probabilitySampler":1}},"sectorbase":{"rootdir":""},"swarm":{"address":"/ip4/0.0.0.0/tcp/26000"},"wallet":{"defaultAddress":"t1usjvldn6hlbhoeph6fzdhojioykzuh6rio3bxga"}},"Disk":{"FSType":"1481003842","Free":31771840512,"Total":31771840512},"Environment":{"FIL_API":"","FIL_PATH":"","GOPATH":"/opt/gopath"},"FilecoinVersion":"fcf56acdc98a2ea4fc4d0b62878a9302f51af869","Memory":{"Swap":0,"Virtual":29515828000},"Runtime":{"Arch":"amd64","Compiler":"gc","GoMaxProcs":32,"NumCGoCalls":838,"NumGoRoutines":884,"NumProc":32,"OS":"linux","Version":"go1.12.1"}}

**Comment by frrist** [comment] 2019-05-29 18:18
Hey @grandhelmsman, based on the information provided here it's hard to tell exactly what the problem is. In the future, any logs or command output you can include from the daemon or commands will be appreciated when trying to debug this.

I do see that your miner has been able to set its price:
```
$ go-filecoin client list-asks | grep t2ysgspglztifypffvfyvv2d6mswdruu37xtsf3da
t2ysgspglztifypffvfyvv2d6mswdruu37xtsf3da 003 0.2 78691
```
and that a client has made a deal with your miner, meaning you have power and are capable of mining a block:
```
$ go-filecoin miner power t2ysgspglztifypffvfyvv2d6mswdruu37xtsf3da
1 / 60331
```
______ 

It is known that there exists at least one miner on the filecoin network who has inappropriately adjusted their block time to be faster than the rest of the nodes and who appears to be ignoring all messages from nodes other than their own. 

This issues is being tracked and address here: https://github.com/filecoin-project/go-filecoin/issues/2834.

It could very well be that at the time you were trying to set your price this miner was mining and ignoring your messages (it's hard to tell).

Since this behaviour is somewhat expected given the current state of the network, and since you were _eventually_ able to set your price and gain power, I am going to close this issue out. However feel free to ask any follow up questions here that come to mind.

**Closed by frrist** 2019-05-29 18:18 UTC
Labels: C-bug

**Comment by frrist** [comment] 2019-05-29 18:42
@grandhelmsman something else here that doesn't add up: The miner address your node is configured to use is `t25n5cxbphqoukk43fg5t3fqd6rrobxs7pnlht2zi` and its wallet address is `t1usjvldn6hlbhoeph6fzdhojioykzuh6rio3bxga` -- both found in the output of the `inspect all` command. The commands you have shared are using addresses that your node does not own, is this a typo?
