### ISSUE TITLE
Is it okay to use osx10.12 with the new proof?

### ISSUE THREAD

**Issue by jscode017** [filecoin-project/go-filecoin#2704] opened 2019-05-02 13:35 UTC
**Describe the bug**

I got something like ld: warning: object file (/Users/jasonwang/go/src/github.com/filecoin-project/go-filecoin/proofs/lib/libfilecoin_proofs.a(persistent_cache_helper.o)) was built for newer OSX version (10.13) than being linked (10.12) 
due to that I'm on osx10.12
Wonder that if it is okay for this?
If so, how can I disable the print of warnings?
**To Reproduce**
After I run go run ./build test
**Screenshots**
ld: warning: object file (/Users/jasonwang/go/src/github.com/filecoin-project/go-filecoin/proofs/lib/libfilecoin_proofs.a(table_properties.o)) was built for newer OSX version (10.13) than being linked (10.12)

**Version information**
mac osx10.12

**Comment by frrist** [comment] 2019-05-02 14:07
Hi @jscode017, without the exact output it is hard to say, would you mind completing the issue template:

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run this command '...'
3. See error

**Screenshots**
If applicable, add logging output or screenshots to help explain your problem.

**Version information**
please fill out this information below completely, it will help us solve your issue faster 
if you are trying to build go-filecoin
- Go: `go version
- Rust: `rustc --version`
- Cargo: `cargo --version`
- Commit: `git rev-parse HEAD`
- Go Env: `$(go env | grep -E "^CC" |  sed -e 's/.*\=//' | sed -e 's/^"//' -e 's/"$//') --version`
- Filecoin Version: `go-filecoin version`

**Comment by jscode017** [comment] 2019-05-02 14:15
Sorry, I update my issue, I'm mainly wondering can I still stick to mac osx10.12?

**Comment by frrist** [comment] 2019-05-02 14:31
I cannot say definitively that you won't have any issues since a mismatch in versions could potentially lead to undefind behavior. However since this is a warning you should be fine. I would suggest upgrading in the future to avoid any issues.

**Comment by jscode017** [comment] 2019-05-02 14:35
Thanks a lot, but are there anyway to not printing it?
my screenshot went something like these
![image](https://user-images.githubusercontent.com/25841989/57083002-6ca02780-6d2a-11e9-9cef-721af17a8eef.png)

**Comment by frrist** [comment] 2019-05-02 15:33
The documentation for `-ldflags` makes me think you can:
```
$ go build -ldflags --help
-extldflags flags
        pass flags to external linker
  -f    ignore version mismatch
  -g    disable go package data checks
  -h    halt on error
```
You could try passing `-f` [here](https://github.com/filecoin-project/go-filecoin/blob/master/build/main.go#L192) when building.

However since I am unable to repo this on my own machine I cannot confirm is this will work. I believe your best bet is to upgrade to OSX Version > 10.12.

**Comment by frrist** [comment] 2019-05-02 17:30
@jscode017 I am going to close this issue since a solution has been given: Updating OS X will alleviate these warning messages.

**Closed by frrist** 2019-05-02 17:30 UTC
Labels: A-build
