### ISSUE TITLE
Error creating payment: context deadline exceeded

### ISSUE THREAD

**Issue by OdysLam** [filecoin-project/go-filecoin#3370] opened 2019-09-09 17:29 UTC
**Describe the bug**:
Can't propose storage-deal. Keep getting 
"Error: error creating payment: context deadline exceeded" with every storage miner that I have tried.

Any ideas?

- Filecoin Version: 0.4.6

**Comment by ZenGround0** [comment] 2019-09-09 18:24
Duplicate of #3316 

We are working on a fix.  This appears related to block chain consensus issues caused by recent changes to the chain syncing subsystem.

**Closed by ZenGround0** 2019-09-09 18:24 UTC
Labels: C-bug

**Comment by OdysLam** [comment] 2019-09-11 16:36
Thanks @ZenGround0  for the swift response!

Looking forward for the fix and the PR, can't wait to experiment again.
