### ISSUE TITLE
[bug] Challenge seed fails to generate if proving period lands on null block

### ISSUE THREAD

**Issue by travisperson** [filecoin-project/go-filecoin#3017] opened 2019-07-04 19:45 UTC
**Describe the bug**

If a miners proving period start happens to turn out to be a null block, we fail to sample the chain as we can't find the block.

filecoin-3: `failed to calculate PoSt: failed to fetch PoSt challenge seed: error sampling chain for randomness: sample height out of range: 2136`

https://explorer.test.kittyhawk.wtf/blocks/zDPWYqFD5RcMoJ1LDuemGXu9jdeZd1dbDfSSAG8x1SzvnBVX9Gx3

filecoin-2: `failed to calculate PoSt: failed to fetch PoSt challenge seed: error sampling chain for randomness: sample height out of range: 2125`

https://explorer.test.kittyhawk.wtf/blocks/zDPWYqFCtuSB3Z6z3Po2sshrQMpgGmoo4cTBqqRH8GaVvKamPVms

https://github.com/filecoin-project/go-filecoin/blob/81e75fd7f9722f9a100b8d03852e4e823a4b209d/sampling/chain_randomness.go#L31-L41

**Expected behavior**
Miners should be able to generate a PoSt seed if their proving period starts on a null block.

**Additional context**

**Comment by travisperson** [comment] 2019-07-05 15:51
filecoin-4 hit this issue a while later `failed to calculate PoSt: failed to fetch PoSt challenge seed: error sampling chain for randomness: sample height out of range: 3142`

**Comment by anorth** [comment] 2019-07-07 23:46
I'm looking into this now. As I understand it, this bug has probably existed in recent releases, but we've recently shortened the proving period by 20x, so are seeing many more proofs, and opportunities for proving to fail.

**Comment by ZenGround0** [comment] 2019-07-08 14:46
FYI root cause was that the guarantee assumed by the challenge sampling code that the proving period start would always land on a block height was invalidated by this commit merged during this release: https://github.com/filecoin-project/go-filecoin/commit/331e559db35cc2c6c98b419c0464cc1ee2d2d73e

**Closed** 2019-07-09 06:11 UTC
Labels: C-bug
