### ISSUE TITLE
[bug] Version missmatch with bootstrap node (v0.1.4)

### ISSUE THREAD

**Issue by evildido** [filecoin-project/go-filecoin#2716] opened 2019-05-04 07:53 UTC
**Describe the bug**
With the last version 0.1.3, go-filecoin daemon reports version missmatch with bootstrap node

**To Reproduce**
Following the  #2059  guide (https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#install-filecoin-and-its-dependencies). I've downloaded go-filecoin ([binary](https://github.com/filecoin-project/go-filecoin/releases/download/test-devnet-0.0.0/filecoin-test-devnet-0.0.0-Linux.tar.gz)).

1- init
> go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car

2- start daemon
> go-filecoin daemon

Output
>  bootstrap.go:137
09:38:53.193 WARNI /fil/hello: code not at same version: peer has version 966fe75919755074c7c2724f2c9634c2b61d4212, daemon has version beecac52e8b86995a050672d0907f5bed4502637, disconnecting from peer: <peer.ID Qm*2DX9XY> hello.go:97
09:38:57.985  INFO    autonat: Discovered AutoNAT peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY notify.go:33
09:39:02.959 WARNI /fil/hello: code not at same version: peer has version 966fe75919755074c7c2724f2c9634c2b61d4212, daemon has version beecac52e8b86995a050672d0907f5bed4502637, disconnecting from peer: <peer.ID Qm*zkFMp4> hello.go:97
09:39:02.960 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*zkFMp4>: stream reset hello.go:170
09:39:13.169 WARNI /fil/hello: code not at same version: peer has version 966fe75919755074c7c2724f2c9634c2b61d4212, daemon has version beecac52e8b86995a050672d0907f5bed4502637, disconnecting from peer: <peer.ID Qm*zkFMp4> hello.go:97
09:39:13.170 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*zkFMp4>: session shutdown hello.go:170
09:39:17.962  INFO    autonat: Discovered AutoNAT peer QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4 notify.go:33
09:39:22.582 ERROR net.bootst: got error trying to connect to bootstrap node {<peer.ID Qm*QvwuiV>: [/dns4/user.kittyhawk.wtf/tcp/9003]}: dial attempt failed: 1 error occurred:
	* <peer.ID Qm*yb58K6> --> <peer.ID Qm*QvwuiV> (/ip4/3.90.230.176/tcp/9003) dial attempt failed: dial tcp4 3.90.230.176:9003: connect: connection refused

**Version information**
- go-filecoin : 0.1.4
- Commit: beecac52e8b86995a050672d0907f5bed4502637 (go-filecoin version)

**note**
Seems to be related with #2685

**Comment by yyh1102** [comment] 2019-05-06 05:23
Same for me. I built the binary from source.

**Comment by frrist** [comment] 2019-05-06 14:12
Hi @evildido, the warning logs from `/fil/hello` are not indicative of an error. There are peers in the network running a different version of filecoin than your own (e.g. a previous version). These errors have since been downgraded in https://github.com/filecoin-project/go-filecoin/pull/2690 as they do not indicte a problem. You can confirm you are connected to peers by running: `go-filecoin swarm peers`.

----------------------------------------

The error message:
```
09:39:22.582 ERROR net.bootst: got error trying to connect to bootstrap node {<peer.ID QmQvwuiV>: [/dns4/user.kittyhawk.wtf/tcp/9003]}: dial attempt failed: 1 error occurred:
* <peer.ID Qmyb58K6> --> <peer.ID QmQvwuiV> (/ip4/3.90.230.176/tcp/9003) dial attempt failed: dial tcp4 3.90.230.176:9003: connect: connection refused
```
occurred as the bootstrap node you were trying to connect to has been taken offline. Your node should have been able to bootstrap itself to other nodes, and you can confirm this by running `go-filecoin swarm peers` and checking that there are nodes connected to you.

@yyh1102 this is the same problem you faced as well.

Closing this as it is not a bug, but feel free to ask any more questions you may have here.

**Closed by frrist** 2019-05-06 14:12 UTC
Labels: C-bug

**Comment by evildido** [comment] 2019-05-06 16:48
Thx @frrist 
`go-filecoin swarm peer` returns empty result 

Same with 0.2.0


another output (with 0.2.0)
`18:46:14.456  INFO    autonat: Discovered AutoNAT peer QmXhxqTKzBKHA5FcMuiKZv8YaMPwpbKGXHRVZcFB2DX9XY notify.go:33
18:46:19.026 ERROR net.bootst: got error trying to connect to bootstrap node {<peer.ID Qm*crmVbg>: [/dns4/user.kittyhawk.wtf/tcp/9004]}: dial attempt failed: 1 error occurred:
	* <peer.ID Qm*9zf5QU> --> <peer.ID Qm*crmVbg> (/ip4/3.90.230.176/tcp/9004) dial attempt failed: dial tcp4 3.90.230.176:9004: connect: connection refused

 bootstrap.go:137
18:46:29.653 WARNI net/identi: error reading identify message:  stream reset id.go:146
18:46:29.653 WARNI /fil/hello: failed to send hello handshake to peer <peer.ID Qm*vwBpp4>: stream reset hello.go:179
18:46:30.210  INFO    autonat: Discovered AutoNAT peer QmXq6XEYeEmUzBFuuKbVEGgxEpVD4xbSkG2Rhek6zkFMp4 notify.go:33
18:46:39.032 ERROR net.bootst: got error trying to connect to bootstrap node {<peer.ID Qm*QvwuiV>: [/dns4/user.kittyhawk.wtf/tcp/9003]}: dial attempt failed: 1 error occurred:
	* <peer.ID Qm*9zf5QU> --> <peer.ID Qm*QvwuiV> (/ip4/3.90.230.176/tcp/9003) dial attempt failed: dial tcp4 3.90.230.176:9003: connect: connection refused

 bootstrap.go:137
18:46:59.103 ERROR net.bootst: got error trying to connect to bootstrap node {<peer.ID Qm*QvwuiV>: [/dns4/user.kittyhawk.wtf/tcp/9003]}: dial attempt failed: 1 error occurred:
	* <peer.ID Qm*9zf5QU> --> <peer.ID Qm*QvwuiV> (/ip4/3.90.230.176/tcp/9003) dial attempt failed: dial tcp4 3.90.230.176:9003: connect: connection refused
`

**Comment by frrist** [comment] 2019-05-06 18:40
@evildido you will be unable to connect to `devnet-user` on version `0.2.0` since `0.2.0` isn't deployed on that devnet yet. Your daemon will need to be version `0.1.4` in order to connect to `devnet-user`, the process for getting setup on `0.1.4` is defined [here](https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started#installing-from-binary).

**Comment by evildido** [comment] 2019-05-06 19:44
@frrist The output was on 0.1.4.

But after restarting the daemon later this evening, I'm able to get peers and sync the blockchain.
Thx for your assistance.
