### ISSUE TITLE
Daemon panic during chain sync

### ISSUE THREAD

**Issue by duduppp** [filecoin-project/go-filecoin#3102] opened 2019-07-23 03:21 UTC
### Description
block:

Block Details
Miner:  t2fk3rbjlsvgwz6vm4v2huwhsxcjxoo4vgrkgp25i
Weight: 11220.000
Height: 103
Nonce:  0
Timestamp:  1562703879

error  :

oroutine 399751 [select]:
github.com/whyrusleeping/yamux.(*Stream).Read(0xc0131b5d40, 0xc0565b7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/whyrusleeping/yamux@v1.1.5/stream.go:134 +0x238
github.com/libp2p/go-libp2p-swarm.(*Stream).Read(0xc013d33450, 0xc0565b7000, 0x1000, 0x1000, 0x1ee1440, 0xc00b239730, 0x5bd9ef)
	/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.0.2/swarm_stream.go:64 +0x64
github.com/multiformats/go-multistream.(*lazyServerConn).Read(0xc013798330, 0xc0565b7000, 0x1000, 0x1000, 0x0, 0x1ee1440, 0x0)
	/go/pkg/mod/github.com/multiformats/go-multistream@v0.0.1/lazyServer.go:32 +0x76
github.com/libp2p/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc04a06b1c0, 0xc0565b7000, 0x1000, 0x1000, 0x0, 0x9, 0xc03c289a60)
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.0.16/p2p/host/basic/basic_host.go:731 +0x52
github.com/jbenet/go-context/io.(*ctxReader).Read.func1(0xc04a06b240, 0xc0565b7000, 0x1000, 0x1000, 0xc013821800)
	/go/pkg/mod/github.com/jbenet/go-context@v0.0.0-20150711004518-d14ea06fba99/io/ctxio.go:108 +0x55
created by github.com/jbenet/go-context/io.(*ctxReader).Read
	/go/pkg/mod/github.com/jbenet/go-context@v0.0.0-20150711004518-d14ea06fba99/io/ctxio.go:107 +0xc4

rax    0x0
rbx    0x20704710
rcx    0xffffffffffffffff
rdx    0x6

How to Solve the Problem？

**Comment by frrist** [comment] 2019-07-23 21:04
Thanks for the issue report. Could you include details below so we can investigate?

**Describe the bug**
A clear and concise description of what the bug is. What were you doing when this happened, please include all logs and full stacktrace.

**To Reproduce**
How can someone reproduce this bug

**Please Provide**
 - OS: [e.g. iOS]
 - Version: `go-filecoin version`
- Output of: `go-filecoin inspect all`

**Additional context**
Add any other context about the problem here.

**Comment by duduppp** [comment] 2019-07-24 02:02
OS:   centos7 
Version: go-filecoin  0.3.2  release 

Output of:   10:00:01.135  INFO chain.sync: fetching the chain, 14500 blocks fetched syncer.go:210
  after  output error 

goroutine 61947 [select]:
github.com/whyrusleeping/yamux.(*Stream).Read(0xc02fb83440, 0xc04b855000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/go/pkg/mod/github.com/whyrusleeping/yamux@v1.1.5/stream.go:134 +0x238
github.com/libp2p/go-libp2p-swarm.(*Stream).Read(0xc054692b40, 0xc04b855000, 0x1000, 0x1000, 0x0, 0xc013566cb8, 0x3)
	/go/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.0.2/swarm_stream.go:64 +0x64
github.com/multiformats/go-multistream.(*lazyServerConn).Read(0xc04e5a87e0, 0xc04b855000, 0x1000, 0x1000, 0x5be291, 0xc054692c30, 0xc013566cc8)
	/go/pkg/mod/github.com/multiformats/go-multistream@v0.0.1/lazyServer.go:32 +0x76
github.com/libp2p/go-libp2p/p2p/host/basic.(*streamWrapper).Read(0xc0423216c0, 0xc04b855000, 0x1000, 0x1000, 0xab7c4a, 0xc013566d0f, 0xc0000e4c00)
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.0.16/p2p/host/basic/basic_host.go:731 +0x52
bufio.(*Reader).fill(0xc00b5d9860)
	/usr/local/go/src/bufio/bufio.go:100 +0x10f
bufio.(*Reader).ReadByte(0xc00b5d9860, 0xab43be, 0x1c214e0, 0x40)
	/usr/local/go/src/bufio/bufio.go:249 +0x39
encoding/binary.ReadUvarint(0x1fe47c0, 0xc00b5d9860, 0x0, 0xc012bc1bc0, 0xc013566da0)
	/usr/local/go/src/encoding/binary/varint.go:110 +0x7b
github.com/gogo/protobuf/io.(*varintReader).ReadMsg(0xc04e59e940, 0x1ffa780, 0xc054692c30, 0x0, 0x0)
	/go/pkg/mod/github.com/gogo/protobuf@v1.2.1/io/varint.go:110 +0x3e
github.com/ipfs/go-bitswap/message.FromPBReader(0x7fada41225a8, 0xc04e59e940, 0xc04e59e940, 0x7fada41225a8, 0xc04e59e940, 0x200dce0)
	/go/pkg/mod/github.com/ipfs/go-bitswap@v0.0.2/message/message.go:173 +0x74
github.com/ipfs/go-bitswap/network.(*impl).handleNewStream(0xc0000e4a40, 0x200cfe0, 0xc0423216c0)
	/go/pkg/mod/github.com/ipfs/go-bitswap@v0.0.2/network/ipfs_impl.go:189 +0x1c8
github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).SetStreamHandler.func1(0xc0523d8440, 0x13, 0x7fada4122478, 0xc0423216c0, 0x1515a, 0xc00944e4d0)
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.0.16/p2p/host/basic/basic_host.go:374 +0x9d
created by github.com/libp2p/go-libp2p/p2p/host/basic.(*BasicHost).newStreamHandler
	/go/pkg/mod/github.com/libp2p/go-libp2p@v0.0.16/p2p/host/basic/basic_host.go:276 +0x6a0

rax    0x0
rbx    0x23ffff70
rcx    0xffffffffffffffff
rdx    0x6
rdi    0x2337
rsi    0x233a
rbp    0x1
rsp    0x7fada650e418
r8     0x0
r9     0x9
r10    0x8
r11    0x202


I don't know what's wrong. I'm in a hurry. 
Thank you for your reply.

**Comment by frrist** [comment] 2019-07-25 17:04
@duduppp this output is truncated. Without the full stacktrace we will be unable to debug this problem further. Please provide the full stacktrace -- usually starts with `panic`.

Can you also provide the output of `go-filecoin inspect all` and how much memory your system has (`free -m`)?

**Comment by duduppp** [comment] 2019-07-29 00:55
what is  "usually starts with panic" ?

it‘s from the beginning to the end of the error!

 My computer's memory is 4G,Do you think it's too little?

My other computer, Depin, is normal.

There is another problem.

Why does my node synchronize properly and set everything up properly?
But there is no information about me in "https://stats.kittyhawk.wtf/storage/mining". I don't know why. Can you tell me?

**Comment by frrist** [comment] 2019-07-29 20:46
> what is "usually starts with panic" ?

Stacktrace's in go start with the word `panic`, for an example see [here](https://gobyexample.com/panic). The stacktrace provided above appears to be truncated/incomplete. We will be unable to troubleshoot this issue without more information.

> Why does my node synchronize properly and set everything up properly?
But there is no information about me in "https://stats.kittyhawk.wtf/storage/mining". I don't know why. Can you tell me?

This is likely because you haven't connected to the dashboard, see these [wiki instructions](https://github.com/filecoin-project/go-filecoin/wiki/Explorer-and-Dashboard#network-dashboard) for connecting to the dashboard.

______

Since there is not enough information to solve this problem I am going to close the issue, feel free to reopen when:
1. The full stacktrace can be provided.
2. The output of `go-filecoin inspect all` can be provided.

**Closed by frrist** 2019-07-29 20:46 UTC
Labels: C-bug, I-panic :bomb:
