### ISSUE TITLE
Chain Sync  is very  slowly!

### ISSUE THREAD

**Issue by taylorshuang** [filecoin-project/go-filecoin#2906] opened 2019-06-09 02:18 UTC
I download this resource  filecoin-0.2.2-Linux.tar.gz, but i can not connect to  main devnet according to this tutorial:  https://github.com/filecoin-project/go-filecoin/wiki/Getting-Started. I've been synchronizing for a week, but I still can't keep up with the main network. What should I do?

**Comment by taylorshuang** [comment] 2019-06-09 02:20
I excute this command, and getting this info.  
Block Details
Miner:  t27gvotilvoudxezxxu2atwfc42otsprm6wvt5x6i
Weight: 1644954.560
Height: 260174
Nonce:  0
and the height of main testnet is about 325227

**Comment by taylorshuang** [comment] 2019-06-10 02:03
Anyone tell how to sync data from  mainly test network?thinks!
I have spent one week to sync data from devnet,crazy！

**Comment by rosalinekarr** [comment] 2019-06-10 12:58
@taylorshuang, this is a known issue and something we're currently working on. You'll find more documentation on the problem and what we're doing to fix it in issue #2050. Additionally, I'm closing this issue as it seems to be a duplicate of that one.

**Closed by rosalinekarr** 2019-06-10 12:58 UTC
Labels: C-bug

**Comment by taylorshuang** [comment] 2019-06-10 13:06
Thanks!
