### ISSUE TITLE
[bug] Message to request funds from faucet failed due to mined message with same sender and nonce.

### ISSUE THREAD

**Issue by frrist** [filecoin-project/go-filecoin#2593] opened 2019-04-16 21:15 UTC
**Describe the bug**
Connected to Usernet and confirmed chain was in sync. Requested funds from the faucet and received message with CID `zDPWYqFCxzKVp9sQx7gM4vWFC56Ngy1C7f5eugdm6KDM4SvkcYP5`. The message was never mined, I confirmed this by waiting 30mins using the command `go-filecoin message wait`.

I inspected the cluster logs and found the [following message](https://search-filecoin-logs-feyxjodkwak6pulqamqtqwgddi.us-east-1.es.amazonaws.com/_plugin/kibana/app/kibana#/doc/1c01a500-b214-11e8-a136-fdb4bed4c560/filebeat-6.5.0-2019.04.16/doc?id=15250aa0-c650-4046-81ae-b0942b09de7d&_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))):

```
Queued message SignedMessage cid=[zDPWYqFCxzKVp9sQx7gM4vWFC56Ngy1C7f5eugdm6KDM4SvkcYP5]: {
"meteredMessage": {
  "message": {
      "to": "t1mdcirsrzmhwootwmksg26i2xzjbddr5jrhcnygq",
      "from": "t1dncjz3lifvl4edelzyy4uxlcitxsyhlukuff54q",
      "nonce": "19744",
      "value": "1000",
      "method": "",
      "params": null
    },
    "gasPrice": "0",
    "gasLimit": "0"
  },
  "signature": "lib4TXDYbG2GxzQlUAAeFAzSHXeDVGwp0Aqd+voU8b95ZmnWFrcqmWd5PzJ+mdF906j6MU+5jQBWA65CNWOPvQA="
} differs from mined message SignedMessage cid=[zDPWYqFCtRvVeDa8Tdt7D8egLtPGh4T8AR4nMnqTrdMXCqioNvqJ]: {
  "meteredMessage": {
    "message": {
      "to": "t1d4rwiflbbx2e3b2ku62r7wypovqgq2zlh6lgaci",
      "from": "t1dncjz3lifvl4edelzyy4uxlcitxsyhlukuff54q",
      "nonce": "19744",
      "value": "1000",
      "method": "",
      "params": null
    },
    "gasPrice": "0",
    "gasLimit": "0"
  },
  "signature": "nk2mwLtPcyav+EV3ZYzjfBOGGjA5pDbnFiRCunqa0bgK2mvV8uTV05Qlfb4o13HCqYiivyFmW8/KPA1YnQXE0AE="
} with same sender & nonce

```

The second time I requested funds from the faucet I was able to retrieve them as expected.

**To Reproduce**
I am not able to reproduce this bug, but if I was going to try I would: Request funds from faucet, inspect logs for similar error message, if it does not exist: lather, rinse, repeat -- this does not appear to be a deterministic bug. 

**Expected behavior**
My node receives funds from the faucet when I make a request here: http://user.kittyhawk.wtf:9797/

**Version information**
I am filling this issue on behalf of another user who asked for help in #fil-help. The thread of discussion can be found here: https://filecoinproject.slack.com/archives/CEGN061C5/p1555435904024300

**Comment by RobQuistNL** [comment] 2019-04-16 21:22
☝️ I'm the one that experienced the bug. Thanks for filing it @frrist! If anyone has any questions, feel free to ping me.

**Comment by RobQuistNL** [comment] 2019-04-16 21:23
Specs of machine:
```
fs@desktop-fs:~$ go-filecoin version
commit: 966fe75919755074c7c2724f2c9634c2b61d4212
fs@desktop-fs:~$ uname -a
Linux desktop-fs 4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
fs@desktop-fs:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.2 LTS"
```

**Comment by rosalinekarr** [comment] 2019-04-17 13:56
I think this may already be resolved by @acruikshank's recent change in #2522, which hasn't gone into devnet yet. @acruikshank, can we confirm that?

**Comment by travisperson** [comment] 2019-04-17 20:35
I think #2522 only addresses changes to the "inbox" `MsgPool`, and this error is in relation to the outbox.

We use both the outbox message queue and the chain head when we compute the next nonce.
https://github.com/filecoin-project/go-filecoin/blob/966fe75919755074c7c2724f2c9634c2b61d4212/plumbing/msg/sender.go#L131-L144

My assumption is we have a race between when we call `LatestState` (note: since refactored) and `nextNonce` where a new tipset has come in and removed the messages from the outbox.
https://github.com/filecoin-project/go-filecoin/blob/966fe75919755074c7c2724f2c9634c2b61d4212/plumbing/msg/sender.go#L79-L89

This would result in a nonce reuse.

**Comment by travisperson** [comment] 2019-04-17 20:47
I'm not too familiar with the `MessageQueue`, @anorth might be able to provide an actual answer to this. I'm not completely sure how the queue / policy stuff works. I think `MessageQueue#Enqueue` might error in the describe case though.

**Comment by acruikshank** [comment] 2019-04-17 21:27
Yes, @travisperson . The code for #2522 is not deployed yet. The error is being issued from the outbound message queue. I suspect it's WAI and this problem is probably a consensus issue coupled with timeout that may be too short.

@frrist  and I analyzed this a bit. Here's what we know.

1. We've had about 5 of these errors in the last 24 hours. Each was a message from the faucet colliding with another message from the faucet.
2. The error occurs when a mined message arrives in a block, but a different message with the same from address and nonce is currently in the queue.
3. We only had one 'nonce too low' error in the same time frame (it occurred multiple times on all the logging nodes). It was for one of the messages that had a nonce collision in the inbound queue.

Here's a working hypothesis:

1. Someone requests funds from the faucet to be sent to t1d4rwiflbbx2e3b2ku62r7wypovqgq2zlh6lgaci.
2. The AccountActor of the account the faucet sends from is 19744 and its outbound queue is currently empty.
3. The message is assigned nonce 19744, added to the outbound queue and published to the network.
4. Something prevents the network from mining the message for more than 10 rounds (~5 minutes).
5. The faucet node receives a block that does not contain the message to t1d4rwiflbbx2e3b2ku62r7wypovqgq2zlh6lgaci, causing the outbound message queue to time out that message.
6. Someone requests funds to be sent to t1mdcirsrzmhwootwmksg26i2xzjbddr5jrhcnygq.
7. The message queue is empty again and the account actor's nonce is still 19744, so the new message gets nonce 19744.
8. Finally the first message gets mined and arrives at the faucet node.
9. When attempting to remove the processed message from the queue, the inbound message queue finds the new message with the same address and nonce and logs the warning.

In this scenario, we'd still expect the first message to go out onto the network. It would fail processing because it has the same nonce as the other message (or maybe timing would cause it to happen the other way around). This would result in a `nonce too low` error.

#### Questions

1. Why wouldn't the first message have been processed. For this theory to work, the queue would have to see at least one block with a block height 10 higher than the block height when the message was added that does not contain the message, and then get a block that does contain the message. This is hard to explain.
2. Why don't we see more 'nonce too low' errors? Clearly we're attempting to send multiple messages with the same nonce. Is it the case that 4 times out of 5 the later message doesn't make it out on the network?

#### Possible Fixes

Without knowing exactly what happened, it's hard to fix anything. Assuming some part of this theory is correct, it provides evidence that our message timeout (10 rounds) is too short and we should extend it. We should keep digging on the actual causes though.

**Comment by travisperson** [comment] 2019-04-17 22:56
I think that is the correct explanation @acruikshank.

https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFD1G6yzPy7E4yLy2jKFcnLu5VqqfyYGwpPG7f7M5pZKAQR

```

**Comment by travisperson** [comment] 2019-04-17 23:05
I think that is the correct explanation @acruikshank.

We can see the message in block [zDPWYqFD1G6yzPy7E4yLy2jKFcnLu5VqqfyYGwpPG7f7M5pZKAQR](https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFD1G6yzPy7E4yLy2jKFcnLu5VqqfyYGwpPG7f7M5pZKAQR)

To | From | Value | Nonce 
-- | -- | -- | --
t1d4rwiflbbx2e3b2ku62r7wypovqgq2zlh6lgaci | t1dncjz3lifvl4edelzyy4uxlcitxsyhlukuff54q | 1000 | 19744 |   |   | nk2mwLtPcyav+EV3ZYzjfBOGGjA5pDbnFiRCunqa0bgK2mvV8uTV05Qlfb4o13HCqYiivyFmW8/KPA1YnQXE0AE=
t1h7j3ows27gkgxkur3pmfi25fozqd7t3nsmmb3fa | t1dncjz3lifvl4edelzyy4uxlcitxsyhlukuff54q | 1000 | 19745 |   |   | N/70bQAaIoHAlwPHf+OXUrOnEvknzhZeK2pNx9zrcNh81b6/yik8IoRDNuhigxGOSzlC81kL6WZCVQJVu4SwoQA=
t1iouly5lt6tv67fovnf2o6qwec2xb7jaj222hbhi | t1dncjz3lifvl4edelzyy4uxlcitxsyhlukuff54q | 1000 | 19746 |   |   | Dh17YbHvHCDZPbCuMdHaWRcguJ1ZUKY9ktKliYNifPhzIPwx7O/Zbiq2kWzjiLzqPVjYqWKhwparGS4P4dndwQA=
t1ljwjhdzys7tsrtcqcrjk44isem3ljwoo4ut7j5y | t1dncjz3lifvl4edelzyy4uxlcitxsyhlukuff54q | 1000 | 19747 |   |   | mq4yIEPIMW9Fxt3ua/y6vCliEYKaNLbXIQAr5QsFLZ8hSz2Vna7bIKFuh4m/FuaDMGOwCjOjQw1Jtl+a1bLv2gA=
t1twl5cs3leird4cuqbwqqc6fhanfxsst2x7ia5wa | t1dncjz3lifvl4edelzyy4uxlcitxsyhlukuff54q | 1000 | 19748 |   |   | nkV23n8L+hFM7/WUyIEu808p98Qi1vEijwdUyPx7mM8z/k2Nblnhb0dUPbpBjEFJshVTBGlHQY4Tn9+395X9yAA=
t1x5ne76taxixorornbfqmpwkiqu3bjklbr3ggqey | t1dncjz3lifvl4edelzyy4uxlcitxsyhlukuff54q | 1000 | 19749 |   |   | L7Oxf1k/5dBpOKlAEBXP4K0ZO4uMV30/qvYcHT+2e2sBJptnBrQgV5ObruEKCJA+wQP6C0gY5MHdXkymb8ObLgA=
t1vdhimp4zejo2jmk4nr2d56f6qkcpsyf4ca3ujcy | t1dncjz3lifvl4edelzyy4uxlcitxsyhlukuff54q | 1000 | 19750 |  

Nonce 19744 is the first nonce, so it would make sense that we would see this come back if the messages were removed due to an expiry.

Nonce 19743 was mined in [zDPWYqFCzWZikcq8dxxNMbP7QTydU7AENX81f23bnCvj3F6P2TDV](https://explorer.user.kittyhawk.wtf/blocks/zDPWYqFCzWZikcq8dxxNMbP7QTydU7AENX81f23bnCvj3F6P2TDV), which is exactly 10 blocks prior.

**Comment by rosalinekarr** [comment] 2019-04-18 14:01
@anorth @mishmosh @whyrusleeping, you all may want to take a look at this one

**Comment by travisperson** [comment] 2019-04-18 16:25
Something to note: The first block I mentioned above is at height of 65468, it's parent is 65438, which is a difference of 30. I believe this is due to null blocks. What I'm unsure of is if we use this straight difference or do we actually count the number of blocks when it comes to dealing with expiry.

**Comment by acruikshank** [comment] 2019-04-18 19:04
@travisperson Thanks for this additional research. The only scenario that makes sense looks something like this:

1. The first message is sent at block height < 65428. It gets nonce 19744, arrives in the queue and gets broadcast to the network. Any message coming in after this will get 19745 because the message is in the queue.
2. Block 65438 lands. The first message is now over 10 blocks old and still hasn't been mined. It gets timed out.
3. The second is sent at 65438<block time<65468. It gets nonce 19744 since there's nothing in the queue and the actor's nonce is still 19744.
4. Block 65468 lands. It contains the first message with the same address & nonce but different to address, so we get an error.

So the first message would have to be sent at least 40 blocks before it was mined an received, and another block would have to be mined 10 rounds after the message was sent and not contain it. We're nowhere near the block limit, so this implies the miner just didn't have the message at the time the 65438 block was mined, but somehow the message was available after that for the 65468 block.

**Comment by anorth** [comment] 2019-07-22 02:34
It seems that we can't reproduce this bug and haven't had any reports of it in the past three months. I'll close it shortly unless someone can reproduce or suggest a concrete action.

**Closed** 2019-08-18 23:52 UTC
Labels: C-bug, scheduled-for-close
