### ISSUE TITLE
Can't store file on the network

### ISSUE THREAD

**Issue by markwylde** [filecoin-project/go-filecoin#1965] opened 2019-02-14 23:03 UTC
**Describe the bug**
When I try to upload a 5mb image to a miner, it fails with the error:

```
Error: error creating payment: context deadline exceeded
```

**To Reproduce**
```bash
mark@ubuntu-server:~$ go-filecoin client import ./image.jpg
QmTzynrk39NTSzFyQUpLJCpXLtgmdqJDw1Dg2Tfb5NeiH8
mark@ubuntu-server:~$ export CID=QmTzynrk39NTSzFyQUpLJCpXLtgmdqJDw1Dg2Tfb5NeiH8
mark@ubuntu-server:~$ echo $CID
QmTzynrk39NTSzFyQUpLJCpXLtgmdqJDw1Dg2Tfb5NeiH8
mark@ubuntu-server:~$ go-filecoin client list-asks --enc=json | head | jq
{
  "Miner": "fcqpe2mq3ljxmp095ujq0qa477j8l8nayudrxark0",
  "Price": "0.0000001",
  "Expiry": 4320,
  "ID": 0,
  "Error": null
}
...
mark@ubuntu-server:~$ go-filecoin client propose-storage-deal fcqpe2mq3ljxmp095ujq0qa477j8l8nayudrxark0 $CID 0 2880
Error: error creating payment: context deadline exceeded
```

I should have enough funds:
```
go-filecoin wallet balance fcqh8gfw6frxr8plhnq2n8mwetmng4az54vqjx7jw
499.99994528
```

**Expected behavior**
Expect the file to upload

**Desktop (please complete the following information):**
```
Linux ubuntu-server 4.15.0-45-generic
Ubuntu 18.04.2 LTS
rustc 1.33.0-beta.6
cargo 1.33.0-beta
go version go1.11.5
```

**Additional context**
- The first test file I uploaded (following https://github.com/filecoin-project/go-filecoin/wiki/Storing-on-Filecoin#import-data) worked well, but now even that won't work anymore.
- I have tried multiple asks/miners
- I have tried restarting the daemon too, but the same problem occurs
- No specific errors seem to be output by the daemon

**Comment by travisperson** [comment] 2019-02-14 23:08
Related to #1875

**Comment by phritz** [comment] 2019-02-14 23:47
thanks for the report @markwylde .

1. whats the address you are using? i can see if i can locate what happened in the logs. `go-filecoin address ls`

2. i suspect this is a nonce issue causing the message wait to timeout because of an earlier failed message at some point. rethinking this in #1936 . meanwhile i could you try to the following to get unstuck? `go-filecoin mpool ls` to see the message in your pool and then use `go-filecoin mpool rm <cid>` on each of the cids listed, then try again?

**Comment by markwylde** [comment] 2019-02-14 23:53
@phritz Hi, my address is `fcqh8gfw6frxr8plhnq2n8mwetmng4az54vqjx7jw`

In response to your second point I ran the following:

```bash
mark@ubuntu-server:~$ go-filecoin mpool ls
zDPWYqFCyKuhUe5Hsj93PNfpFjj9hwiqKt9UzNhbvkTGimu39of5
zDPWYqFD43GsK5hyUsgCRasKXiFDfRo39o9RaQx1eoGD2GZmVrS4
zDPWYqFCsUoahcXg2J9PE3G4uA3ADamV3mbtafhFrK6mqxCGpRDL
zDPWYqFD5pQFXTwkyx9byX2LSq2zVJDosFX9iv3XT5q3Q5ZLhGYB
zDPWYqFCuiNhBx9CHGhFhYRdsbKjMx3fKmzBD4tsRCPWMk4U5spp
zDPWYqFD2h6CuUHuSoCYJJk5spHf7jwCxsjW1RXQtxvtgyRWv7uo
mark@ubuntu-server:~$ go-filecoin mpool rm zDPWYqFCyKuhUe5Hsj93PNfpFjj9hwiqKt9UzNhbvkTGimu39of5
mark@ubuntu-server:~$ go-filecoin mpool rm zDPWYqFD43GsK5hyUsgCRasKXiFDfRo39o9RaQx1eoGD2GZmVrS4
mark@ubuntu-server:~$ go-filecoin mpool rm zDPWYqFCsUoahcXg2J9PE3G4uA3ADamV3mbtafhFrK6mqxCGpRDL
mark@ubuntu-server:~$ go-filecoin mpool rm zDPWYqFD5pQFXTwkyx9byX2LSq2zVJDosFX9iv3XT5q3Q5ZLhGYB
mark@ubuntu-server:~$ go-filecoin mpool rm zDPWYqFCuiNhBx9CHGhFhYRdsbKjMx3fKmzBD4tsRCPWMk4U5spp
mark@ubuntu-server:~$ go-filecoin mpool rm zDPWYqFD2h6CuUHuSoCYJJk5spHf7jwCxsjW1RXQtxvtgyRWv7uo
mark@ubuntu-server:~$ go-filecoin mpool ls
```

I then tried to upload the file again:
```
mark@ubuntu-server:~$ go-filecoin client propose-storage-deal fcqmleyv95x3tnd90txkphe8eh7d68x3zg95dadh4 $CID 0 2880
Error: error creating payment: context deadline exceeded
```

The ask I used was:
```
{
  "Miner": "fcqmleyv95x3tnd90txkphe8eh7d68x3zg95dadh4",
  "Price": "5.449670335",
  "Expiry": 4515,
  "ID": 0,
  "Error": null
}
```

**Comment by markwylde** [comment] 2019-02-14 23:55
For reference this is all the asks I get:

```bash
mark@ubuntu-server:~$ go-filecoin client list-asks --enc=json | jq
{
  "Miner": "fcq8vvc6jlrefgmjncl3cplzrraa5932rznp054s6",
  "Price": "3.535359793",
  "Expiry": 4721,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqpe2mq3ljxmp095ujq0qa477j8l8nayudrxark0",
  "Price": "0.0000001",
  "Expiry": 4320,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqlze8qacnpdl5fugrlsxnva5lm0wl5q7lzg52sj",
  "Price": "0.8749228519",
  "Expiry": 2894,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq4s5a2r2j59yk4cw3nuswl3ku0u2hwe5hmll3ys",
  "Price": "12.85195743",
  "Expiry": 4368,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqvvxfstrlcmcsnzfdqd3n7qsucxhl47v4cd8ynw",
  "Price": "7.098555385",
  "Expiry": 2929,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq0cgvatc47yynzlw5lcueg7yhamp5q723gp9kwf",
  "Price": "0.000000001",
  "Expiry": 4285,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq75z5l0ukrswhnyk0fnxeha0sdwg5ns9vmq4nyj",
  "Price": "0.000000001",
  "Expiry": 4679,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq6l6m5x09zpmq0h4xyj5v2ga8x58vn27cg0n0u9",
  "Price": "5.853170123",
  "Expiry": 4284,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqxeln6u3a8dsavgvpgjmxktytxmkpuuc4xtylgy",
  "Price": "4.134518576",
  "Expiry": 4491,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq6xr4natyf0p8wvgywljt3xacj0p2x3qvz7qq9e",
  "Price": "0.000000001",
  "Expiry": 86503,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqwvs3673kharyryf9x77m7vx8ccmt98cqk2rfef",
  "Price": "11.30498294",
  "Expiry": 4554,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqjzx0zul5ht70t3wn3mpk3qmvxyk79lv3kxmaq5",
  "Price": "2.712853884",
  "Expiry": 4481,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqx67mmud2qt6mxdechja6gskw7p4vdwfywgqjv7",
  "Price": "7.502501621",
  "Expiry": 4525,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq7ls4gay8eecw9nra37z9wgfcjvlw23p9gsg54v",
  "Price": "6.062556475",
  "Expiry": 2903,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqxx0zfdwal36952zvadgyk0yspxg2v07qajw6mf",
  "Price": "0.000000001",
  "Expiry": 4554,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqxx0zfdwal36952zvadgyk0yspxg2v07qajw6mf",
  "Price": "0.000000001",
  "Expiry": 4562,
  "ID": 1,
  "Error": null
}
{
  "Miner": "fcqxx0zfdwal36952zvadgyk0yspxg2v07qajw6mf",
  "Price": "0.000000001",
  "Expiry": 4564,
  "ID": 2,
  "Error": null
}
{
  "Miner": "fcq4ljfz375fh7m24ugp6efz3vea8l0edwhgf7fh6",
  "Price": "0.4116091373",
  "Expiry": 4472,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqfqu4nthqjeagqawj4udqs5jdfgx70qsd5xmc8e",
  "Price": "6.526403581",
  "Expiry": 4731,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq86yl5u3vzsded64kankh25q8m0wlpvh02qzccn",
  "Price": "2.796355229",
  "Expiry": 2897,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqrrmesaxy75vme2xnr7vvhlh5ct5flg53hyjgsz",
  "Price": "12.30395399",
  "Expiry": 4543,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqytt3fj0hw60jhaag766he57af6muj30xxfqluy",
  "Price": "13.11514138",
  "Expiry": 2953,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqrntvycn6e45hsn9uaqqd4jes4fzn6f2qvyvv3d",
  "Price": "12.18395342",
  "Expiry": 4376,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqkwepwlv4n4fe2cc9gk3egm6regkg5kzvwy7x56",
  "Price": "55",
  "Expiry": 11492,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqkwepwlv4n4fe2cc9gk3egm6regkg5kzvwy7x56",
  "Price": "60",
  "Expiry": 11499,
  "ID": 1,
  "Error": null
}
{
  "Miner": "fcqkwepwlv4n4fe2cc9gk3egm6regkg5kzvwy7x56",
  "Price": "65",
  "Expiry": 11502,
  "ID": 2,
  "Error": null
}
{
  "Miner": "fcqkwepwlv4n4fe2cc9gk3egm6regkg5kzvwy7x56",
  "Price": "200",
  "Expiry": 11503,
  "ID": 3,
  "Error": null
}
{
  "Miner": "fcqkwepwlv4n4fe2cc9gk3egm6regkg5kzvwy7x56",
  "Price": "500",
  "Expiry": 11506,
  "ID": 4,
  "Error": null
}
{
  "Miner": "fcq7dqfj6lhgh0lqudrtc70ktueht20f4n04035p",
  "Price": "0.000000001",
  "Expiry": 86511,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqn70wv8jym0sne9r0cam73nnvma2d8ttustj9vq",
  "Price": "8.319501442",
  "Expiry": 2937,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqw0hdhz9uqucnn9jzurzn4xgtf652jrg579ggl3",
  "Price": "8.763293427",
  "Expiry": 2948,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq8aj3zx4s62judq0phre0kr4c95ultrcw7r5fwr",
  "Price": "2.184817566",
  "Expiry": 4710,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqhml4gl0m9j74pwraajxv2f2afrf6lzqyefkqqc",
  "Price": "5.346151024",
  "Expiry": 4337,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqyg2ttjcejm3demzzdmv0qqnrne8rw3mk0lvesm",
  "Price": "7.326706495",
  "Expiry": 4345,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqpc25rrq9ltkd86k5pat2pua4xdqrtu6sdg0srq",
  "Price": "13.43455713",
  "Expiry": 4383,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqcj3hqukupes9hkuz2n49kzw9klsnxxk4prkyu9",
  "Price": "1.466848848",
  "Expiry": 4698,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqfxajylu4ya4q6nr4ylvpyawexktye5zxfzdzwy",
  "Price": "0.0000000001",
  "Expiry": 6401,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq2gf6wazgjm9fplj60zs6v04fhfvvtj6uzesm42",
  "Price": "0.000000001",
  "Expiry": 86507,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq478h0gzwsg7e4nq0gpr8spck2drl2v2u87vxg4",
  "Price": "7.713666888",
  "Expiry": 2944,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq5r0jkr909hy0ghxq3d752h3ky67z2htlqewcsy",
  "Price": "0.000000001",
  "Expiry": 86515,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqynveuyegann3wp8azd7sfgjgjg5w7d9yvx7wf",
  "Price": "7.184972882",
  "Expiry": 2927,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqmr7ud7nm0zugxctm8qu78fxdu9mrhgmwcyec5u",
  "Price": "3.722008732",
  "Expiry": 2900,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqkj097cwua7as0f5gjler6q4ug2z670ztgvuln0",
  "Price": "11.0281837",
  "Expiry": 4361,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq35fqhadf0me449fnythlm6ethcpf6un7e0vnr7",
  "Price": "0.000000001",
  "Expiry": 16213,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqn4xsqwfdjq2s9len80kq840uatfvdza7qh7r4y",
  "Price": "2.665213209",
  "Expiry": 4328,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqhz6kw56qz303dfjzevznelf4k9t230j0t7279c",
  "Price": "4.572913322",
  "Expiry": 4499,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqyh7vfl0mm75wjjqmsgnwp8erhzpr6auudxcs0g",
  "Price": "8.601543426",
  "Expiry": 4353,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqc5qgnl6zh3grcd83jqkwjau4lle5unwq8rc0fp",
  "Price": "3.776032322",
  "Expiry": 4278,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqywvcm5cnwjsnm9al0dtf3zm4qgk7a8cg2x9mkq",
  "Price": "0.06215575103",
  "Expiry": 4321,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqcpdty3as9x92h2f887dqxpevjuq9c6h0wkanml",
  "Price": "15.49934692",
  "Expiry": 4390,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqzqkcpsergrmwcpe374euacnmeayelu76enjs05",
  "Price": "11.35200683",
  "Expiry": 2950,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq6ufudt6fc4vvapfk03tlapwfcsf9lx2fhq2vzv",
  "Price": "9.483542911",
  "Expiry": 4535,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqgvw2ztyj9p3jdqn2jecshzudza34csg2jldmnm",
  "Price": "4.31526764",
  "Expiry": 2917,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqzcww52gdd2scl79mqu9emvnstek0pxsl08ar5m",
  "Price": "5.285352123",
  "Expiry": 4506,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcqmleyv95x3tnd90txkphe8eh7d68x3zg95dadh4",
  "Price": "5.449670335",
  "Expiry": 4515,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq423mk77skf2tg2542ku6skje9859ecu3z7dmha",
  "Price": "3.695158894",
  "Expiry": 2911,
  "ID": 0,
  "Error": null
}
{
  "Miner": "fcq32lll8xxtx4el3xdvpqx552xhhxsazw0zpdc4f",
  "Price": "7.638509218",
  "Expiry": 2942,
  "ID": 0,
  "Error": null
}
```

**Comment by markwylde** [comment] 2019-02-14 23:57
I'm happy to delete my `~/.filecoin` directory and start again?

**Comment by phritz** [comment] 2019-02-15 00:10
hmm, i see a few of your createchannel messages that went through then four like this, with nonce too high. that could be accounted for by having old messages that failed for some reason in your mpool, but clearing the mpool should've fixed it. 

would you mind starting over with new .filecoin directory and then running your propose deal command once. when/if it fails once can you post your address, mpool contents, and any output?

```
temporary ApplyMessage failure, [SignedMessage cid=[zDPWYqFCsUoahcXg2J9PE3G4uA3ADamV3mbtafhFrK6mqxCGpRDL]: {   "meteredMessage": {     "message": {       "to": "fcqp606qfk5gwmq6ac24g4mhv3cr8zzf67vqkpulh",       "from": "fcqh8gfw6frxr8plhnq2n8mwetmng4az54vqjx7jw",       "nonce": "Dg==",       "value": "0.00005472",       "method": "createChannel",       "params": "glYAAJuzdu74EtGowb8o63IeMrLVByKEQsc0"     },     "gasPrice": "0",     "gasLimit": "rAI="   },   "signature": "VgUpkgciYWhAhKB1EP+KOlS86szkZMyKVllSO+D/29IN4In9uyNBKKCt5ybYzYVrWIGyREK5dBVSiJO0lj94BQA=" }] (apply message failed: nonce too high)
--



```

**Comment by phritz** [comment] 2019-02-15 00:16
oh, also just before you do the deal proposal could you run `go-filecoin address lookup <mineraddress>` and then `plug the output of that into `go-filecoin swarm findpeer <outputofabove>`.

**Comment by imrehg** [comment] 2019-02-15 10:10
I've tried to store some files as well (just following the getting started guide:) but haven't succeeded either. Seems like I'm not finding any viable/reachable peer. To test that I combined the address lookup, findpeer, and ping. Even then, when I try the peers that I could ping I cannot store. Rerunning the check also quite often don't find the same peers reachable, as if the network is in constant flux?

The script I used was:
```
#!/bin/bash
set -x

function checkminer() {
  local MINER=$1
  local ADDR=$(./go-filecoin address lookup $MINER)
  go-filecoin swarm findpeer $ADDR && \
    go-filecoin ping -n 1 $ADDR && \
    echo -e "\033[0;31m Found viable peer? $MINER / $ADDR \033[0m"
}

ASKS=$(go-filecoin client list-asks --enc=json | jq -r .Miner)
for ask in ${ASKS[@]} ; do
  checkminer $ask
done
```

**Comment by imrehg** [comment] 2019-02-15 10:38
I tried what you proposed above, @phritz, fresh `.filecoin`, and single attempt for a deal

```
$ go-filecoin address ls
fcq0mhjypzl368jk30kh8qc2534kymhum4729wk8l
```

The contents of mpool, I guess this?
```
$ go-filecoin mpool ls
zDPWYqFD45ZFG1azZnuMddprrTGyZvLk6Vy4ce6E6JR53nxvwP8w
zDPWYqFCqq2yucvMeJXtscXrMveNHCKps9y5GR9x27qnv55k8y4g
zDPWYqFD8QuprjAZ6sHiNsRPVQwHYWorRcKNG9juKR6iLRYvrHru
zDPWYqFCzYUbUyz9bwzEh6zKGizPGarctYCbPL9zVruD5EMhPc7g
zDPWYqFCwCEX5NLQmQ9CKr2sdtZerjmyDB3WAGEv3LPUx8GhkE72
zDPWYqFD1SMKwRmAYku5UBKZaDq9xhEmWeZnkHpcz8N8PXdRJxkE
zDPWYqFCvDsELcpR2dtkSsGePTAkTgDxKgDiEmJmffdMSdK53XiE
zDPWYqFCyMNB3jQsrfyfGghLXiZiV21E8ye7kTsVK1QsBz215jAA
zDPWYqFD4RQX8bL5VBv3vshLpExtfFU7iocnhgvG51PxxoH1BUCj
zDPWYqFCwAbeL5nkqRRyN5Ffyir2oYpLeArDiuDnCrq23PFrQRZy
zDPWYqFCuoFZCkNz26W23ee9nutf8EUQrcR8uQR68FR3Bw39Hp1g
zDPWYqFCvyGdwhgKNBBNyEiXMufFuFPRdz62iJgxYcDq6Bqu4zTA
```

I've looked up a viable peer witht the script above, and running the add resulted in:
```
$ go-filecoin client propose-storage-deal fcq6xr4natyf0p8wvgywljt3xacj0p2x3qvz7qq9e $CID 0 100
Error: error creating payment: context deadline exceeded
```

I'm running from this commit:
```
$ go-filecoin version
commit: 271a6812e23e3ccd80642d251e1c1f449459a8b7
```

**Comment by magik6k** [comment] 2019-02-15 16:11
I'm also having this problem, re-trying few times (5-10), with calling `go-filecoin mpool ls | xargs -L1 go-filecoin mpool rm` on both sides seemed to make it eventually work

**Comment by magik6k** [comment] 2019-02-15 20:23
So when I create new storage deal with:

```
go-filecoin client propose-storage-deal fcq973y2y7hvcce8zkwds7r2847xmfjvdecn98lws QmRv4nmzja2osHpLSzZKGWbdd9G9g4CtFfU8uf5ZVTXgEq 2 50
```

On node A (client), I can see that in hangs on https://github.com/filecoin-project/go-filecoin/blob/master/porcelain/payments.go#L120.

On node B (miner, with no sealed blocks, but still mining) I can see the hash in  `go-filecoin mpool ls`, but on neither A nor B am I able to view the CID with `go-filecoin dag get`

**Comment by travisperson** [comment] 2019-02-15 20:26
@magik6k you got `QmRv4nmzja2osHpLSzZKGWbdd9G9g4CtFfU8uf5ZVTXgEq` from using `go-filecoin client import` on node A correct?

**Comment by magik6k** [comment] 2019-02-15 20:26
Yep

**Comment by magik6k** [comment] 2019-02-15 20:26
It's a 50G random file

**Comment by travisperson** [comment] 2019-02-15 20:31
That probably explains why you can't propose the deal. We don't currently manage the deal chunking. `propose-storage-deal` must fit into a sector. The user devnet has a sector size of 256MiB (note: max import size is `266338304` due to overhead).

**Comment by magik6k** [comment] 2019-02-15 20:54
Yeah, smaller files seem to work for me.

**Comment by markwylde** [comment] 2019-02-16 11:45
@phritz I tried again, fresh `~/.filecoin` directory and same issue. I tried a few different asks too, but all had the same, except the last one I tried which gave "Error: error sending proposal: could not establish connection with peer. Peer does not support protocol". But that seems like it's just using a different version.

Anyway the results from are below:
![image](https://user-images.githubusercontent.com/5929807/52899272-313c9500-31e0-11e9-9316-5726abb818da.png)

**Comment by rafael81** [comment] 2019-02-19 12:49
I have same problem and I have a questions.
If my node isn't the latest block, can't I trade in storage?
"Error: error creating payment: context deadline exceeded"
I can't even step forward because of this error message.

**Comment by anorth** [comment] 2019-02-20 03:49
I have added notes to https://github.com/filecoin-project/go-filecoin/wiki/Troubleshooting-&-FAQ about the maximum piece size and the need to connect directly to the miner in question. We should clearly produce better error messages for these cases.

It's not clear to me whether there's another issue here lurking under the UX minefield.

@markwylde I believe the `dial backoff` error is coming from the libp2p library internally, which has some built-in throttling that's not helping us here. You may need to wait a minute after a failed attempt.

**Comment by anorth** [comment] 2019-02-20 03:59
Ah, yes it's probably the nonce issue #1936.

**Comment by rjan90** [comment] 2019-02-20 16:41
Had the samme issue, getting ´Error: error creating payment: context deadline exceeded´, when trying to propose a storage deal between my two nodes. Clearing mpool on both my nodes fixed the problem.

**Comment by Nanofortress** [comment] 2019-02-21 15:33
Also having this error when trying to store files, ```Error: error sending proposal: could not establish connection with peer. Peer does not support protocol```. 

I have 2 nodes in my setup, one on Mac OS 10.14.2 and the other on Ubuntu 18.04.1 . When trying to make a deal from my Mac to Ubuntu it works, but when I tried to make a deal from Ubuntu to Mac it fails giving the error above.

On a side note making the deal took me at least 30 seconds from Mac to Ubuntu, and it took around 4 mins before the file is posted. While making the deal from Ubuntu to Mac took more than 30 seconds and then it spits out the error above.

**Comment by woshihanhaoniao** [comment] 2019-02-21 21:37
sorry idon't in english ,the text form google . I'm depressed now because I want to transfer files between my two computers. But now they can only upload files, but they can't save them. All the tips are  

 `_Error: error creating payment: context deadline exceeded_`

I don't know what to do. Thank you very much for your help.

**Comment by woshihanhaoniao** [comment] 2019-02-21 21:47
_./go-filecoin mpool ls | xargs -L1 ./go-filecoin mpool rm_

I executed these sentences on both computers, but the problem remained unsolved.

**Comment by woshihanhaoniao** [comment] 2019-02-21 21:48
### ./go-filecoin mpool ls | xargs -L1 ./go-filecoin mpool rm

I executed these sentences on both computers, but the problem remained unsolved.

**Comment by woshihanhaoniao** [comment] 2019-02-21 21:48
`./go-filecoin mpool ls | xargs -L1 ./go-filecoin mpool rm`

I executed these sentences on both computers, but the problem remained unsolved.

**Comment by woshihanhaoniao** [comment] 2019-02-22 01:21
@markwylde

**Comment by phritz** [comment] 2019-02-26 06:33
hi all, we have some pretty bad ux issues that as anorth mentions may or may not be masking more problems. we are actively working on in https://github.com/filecoin-project/go-filecoin/issues/2028 but it will take us a few weeks to land them. our next user devnet release will be either end of march or early april. the best thing to do is to wait until that time and we can try again, hopefully with more debug output and fewer avoidable message pool issues. apologies that you are having so much trouble. 

@Nanofortress that timing is not surprising, sealing data into sectors could take minutes. i am surprised by the 'peer does not support protocol' error, might be related to some libp2p problems we have been having that should be addressed in the next release.

**Comment by pengxiankaikai** [comment] 2019-02-27 08:42
@phritz I also encountered the same problem. Is this problem solved now? thanks!

**Comment by Nanofortress** [comment] 2019-03-01 16:55
@phritz I found out what that error was. It turned out I forgot to start mining after restarting the node. :p  
But afterwards I got the same error ```Error: error creating payment: context deadline exceeded```.
This always occurs after the command has ran for 2 mins 1 secs mark as shown below. Maybe extending the deadline helps?
```bash
[11:34:25] edwin.zhou@Edwin-mac-2:~/Desktop$ go-filecoin client propose-storage-deal $id $text 0 100
Error: error creating payment: context deadline exceeded
[11:36:26] edwin.zhou@Edwin-mac-2:~/Desktop$ 
[11:37:33] edwin.zhou@Edwin-mac-2:~/Desktop$ go-filecoin client propose-storage-deal $id $text 0 100
Error: error creating payment: context deadline exceeded
[11:39:34] edwin.zhou@Edwin-mac-2:~/Desktop$
```

**Comment by yangjian102621** [comment] 2019-03-04 09:32
I had got the similar problem:

```
xjxh@xjxh-PowerEdge-T110-II$ export CID=`go-filecoin client import sample-data-master/camel.jpg`
xjxh@xjxh-PowerEdge-T110-II$ go-filecoin client propose-storage-deal fcqdzp28x8vnph7aedzw3pwlpwrnxjh77zayx75c5 $CID 0 2880
Error: error sending proposal: could not establish connection with peer. Peer does not support protocol
```
Has anyone solved this problem?

**Comment by anorth** [comment] 2019-03-26 23:36
We have released a new user devnet (tag `0.1.4`) which we expect to resolve many of these issues. I'm going to close this now-old issue in favour of existing and new issues that we discover in the new release.

**Closed by anorth** 2019-03-26 23:36 UTC
Labels: C-bug

**Comment by a8159236** [comment] 2019-03-28 07:36
1, submitted the size of the space, but the dashboard does not show my contribution to the hard disk space
2. After uploading the file successfully, it cannot be accessed through ipfs.io/ipfs/HASH.

**Comment by yangjian102621** [comment] 2019-03-28 08:36
@a8159236 

Hi here.

1. Your contribution will not show immediately on dashboard after submitting the file. Because the state of your deal is still `staged` not `posted`, you can query you deal state use the following command:

```
go-filecoin client query-storage-deal <dealID>
```

Only if your miner finished the sealing process and submit the Proof of Replication, the dashboard will show your contribution.

2. The filecoin Decentralized Storage Network is not same as the `ipfs.io`, there a two difference network, so you can not access file through `ipfs.io`, you should use the `retrieval-client` command to get your file with following command:

```
go-filecoin retrieval-client retrieve-piece <minerAddress> <CID>
```

**Comment by a8159236** [comment] 2019-03-28 09:15
1、How can I query <dealID>
2、What do these two words mean?（staged and posted）
Can you explain it to me? Thank you.

**Comment by a8159236** [comment] 2019-03-28 09:16
1、How can I query  <dealID>
2、What do these two words mean?（staged and posted）
Can you explain it to me? Thank you.

**Comment by a8159236** [comment] 2019-03-28 09:17
1、How can I query  dealID
2、What do these two words mean?（staged and posted）
Can you explain it to me? Thank you.

**Comment by a8159236** [comment] 2019-03-29 02:30
Error: error sending proposal: could not establish connection with peer. Peer does not support protocol；
What is the cause of this error?

**Comment by a8159236** [comment] 2019-03-29 02:32
Error: error sending proposal: could not establish connection with peer. Peer does not support protocol；
What is the cause of this error?I am prompted for this error when transferring files from one mining machine to another.

**Comment by yangjian102621** [comment] 2019-03-29 04:40
@a8159236 

You shuld run `go-filecoin mining start`  before on the miner node.

**Comment by a8159236** [comment] 2019-03-29 04:50
Thank you very much for solving the problem, but there is a problem. I have been transmitting data before, and suddenly I can't pass the transmission after several consecutive transmissions. Need to start again? What is the reason
问题解决了非常感谢，但是有一个问题，我之前传数据还正常，突然连续传输几次就传不了掉线了，需要重新开始？这是什么原因

**Comment by a8159236** [comment] 2019-03-29 04:58
Thank you very much for solving the problem, but there is a problem. I have been transmitting data before, and suddenly I can't pass the transmission after several consecutive transmissions. Need to start again? What is the reason
问题解决了非常感谢，但是有一个问题，我之前传数据还正常，突然连续传输几次就传不了掉线了，需要重新开始go-filecoin mining start？这是什么原因 @yangjian102621

**Comment by yangjian102621** [comment] 2019-03-29 06:42
@a8159236 

Sorry, i don't know the real reason for your problem.

One of possible reason may be when you run `client propose-storage-deal` the miner will start sealing process and submit the Proof of Replication.
if you send many deal in a row,  the sealing process will consume a lot of cpu and ram resource, so your miner node may stop mining sometime even crashed if you did not have enough ram.

**Comment by ytQiao** [comment] 2019-03-29 08:36
I also encountered some problems. 
1. I have stored more than 256 MIB files to the same miner. After a long time, I used the  `go-filecoin client query-storage-deal <dealID>` query, the status is still in staged, is this related to What is the miner's sealing speed?
2. Does the miner storage machine have higher performance requirements? @yangjian102621

**Comment by yangjian102621** [comment] 2019-03-29 10:40
@ytQiao 

1, The sealing speed will not be too fast, in fact it is deliberately designed to prevent Sybil attack, outsourcing attacks and generation attacks. [Get more information of PoR](https://github.com/filecoin-project/specs/blob/master/proofs.md)
2. Another reason that why your sealing process is too long is you had stored more than 256 MB data to the same miner, so it must finish 2 sectors sealing work, even if you just stored 256.01 MB files. Because 
 sectors are always padded out to the full size, 0.1 MB data will sealing to another sector.
3. I'm not sure if the miner node need a better requirements, but a better requirements will improve your success rate.
4. It didn't provide what's the good numbers for system requirements of miner node in the README file, but 8GB ram at least for miner.

**Comment by 814556001** [comment] 2019-04-01 01:33
Someone stored data in the space I provided, why I haven't shown that I got the block, how can I get the block.

**Comment by a8159236** [comment] 2019-04-08 01:25
Hello, can you ask a question again? How do I change if I want to change the path to the .filecoin folder? @yangjian102621

**Comment by yangjian102621** [comment] 2019-04-08 01:42
> Hello, can you ask a question again? How do I change if I want to change the path to the .filecoin folder? @yangjian102621

@a8159236 

By run the filecoin daemon with the `repodir` flag

```
go-filecoin daemon --repodir=<your data path>
```

**Comment by a8159236** [comment] 2019-04-08 01:49
alright, thank you very much @yangjian102621

**Comment by a8159236** [comment] 2019-04-13 08:05
@phritz Hi, I uploaded more than 256MB of files, but I have been in the "staged" state so far, why haven't "posted" for so long? Is it because the uploaded content is too large? Still because of computer performance, but all the files I uploaded add up to about 500MB.

**Comment by anorth** [comment] 2019-04-14 22:49
@a8159236 I think your requests would be better in either the [Filecoin discussion forum](https://discuss.filecoin.io/) or slack/matrix than this issue. We can open a new issue if we can determine a bug is involved.

**Comment by a8159236** [comment] 2019-04-15 00:51
alright, thank you very much @anorth

**Comment by a8159236** [comment] 2019-04-25 06:13
@yangjian102621 Hello, I want to ask, I change the storage paths Filecoin steps is what kind of, first `go-filecoin init --devnet-user --genesisfile=https://genesis.user.kittyhawk.wtf/genesis.car` and then `go-filecoin daemon --repodir=<your data path>`? and then `go-filecoin daemon` ?

**Comment by a8159236** [comment] 2019-05-09 06:05
@anorth Hi,after installing the new version, 'Error: dial backoff' appears when transferring data. When I ping, I cannot ping successfully

**Comment by anorth** [comment] 2019-05-09 11:02
Failing to ping or transfer data may indicate that the miner you are
attempting to reach is offline. The network has no control over when miners
may choose to go offline.

Are you proposing a deal to a miner node that you are operating? Are you
sure it's online?

**Comment by a8159236** [comment] 2019-05-09 14:23
@anorth Ok, thanks. The problem has been solved because of the network
