### ISSUE TITLE
Investigate DHT put issue (go-libp2p-kad-dht)

### ISSUE THREAD

**Issue by laser** [filecoin-project/go-filecoin#437] opened 2018-05-15 13:31 UTC
Split out from @whyrusleeping 's original [catch-all issue](https://app.zenhub.com/workspace/o/filecoin-project/go-filecoin/issues/351).

### Description

Address issues described [here](https://github.com/libp2p/go-libp2p-kad-dht/issues/139).

### Acceptance criteria

TBD

### Risks + pitfalls

TBD

### Where to begin

TBD

**Comment by whyrusleeping** [comment] 2019-02-23 01:21
@raulk its not so much the DHT put, but the issues that were plaguing it. I *think* that the dial issue you fixed recently might have been the root cause actually.

**Comment by raulk** [comment] 2019-02-26 21:14
@whyrusleeping that makes sense. Puts make lots of dials to lookup the K=20 closest peers to the key, then sends PutValue RPCs to them. If the dialer was stalling, it would somewhat explain the behaviour observed here.

Do we want to close this issue and reopen if we notice it again?

**Comment by whyrusleeping** [comment] 2019-02-27 18:49
Yeah, let's close for now. Hopefully its fixed :)

**Closed by whyrusleeping** 2019-02-27 18:49 UTC
Labels: M-deps
