### ISSUE TITLE
[bug]can't get Fil token anyway!

### ISSUE THREAD

**Issue by windstore** [filecoin-project/go-filecoin#2333] opened 2019-03-19 05:26 UTC
when i got token from the url http://user.kittyhawk.wtf:9797/，it responsed “Failed to parse target address t1nv5ub4verxbefiwo2zrb47zcjayjdvmkqp4onoy invalid character”。

In another way，I tried from cmd, it responsed “Error: invalid message cid: illegal base32 data at input byte 0”.

so,what's the problem?

**Comment by rosalinekarr** [comment] 2019-03-19 14:31
> t1nv5ub4verxbefiwo2zrb47zcjayjdvmkqp4onoy

This string contains a `1`, which means it isn't a valid base32 encoding.

I suspect we broke something in switching over to base32.

@frrist, would you mind digging into this when you have the time?

**Comment by rosalinekarr** [comment] 2019-03-19 14:34
@windstore, thank you for pointing out this problem!

**Comment by travisperson** [comment] 2019-03-19 15:28
This is a new address from the recently merged address code. To connect to the user devnet you will need to be using the tagged code `devnet-user`.

There might be some issues building that tag at the moment though, you can try to download the binary release for your platform from the [releases page](https://github.com/filecoin-project/go-filecoin/releases/latest). You can use the nightly devnet if you run into issues. The nightly resets @ 0600 UTC, you can find the correct version in the README.

**Comment by frrist** [comment] 2019-03-19 16:18
This is not a bug with the address code -- the problem, as @travisperson has already pointed out, is the version of go-filecoin @windstore is using is not compatible with the version of go-filecoin the user devnet is running.

**Closed by frrist** 2019-03-19 16:18 UTC
Labels: C-bug

**Comment by windstore** [comment] 2019-03-20 02:26
Great job，Thanks！
