### ISSUE TITLE
Use go-address module in go-filecoin

### ISSUE THREAD

**Issue by acruikshank** [filecoin-project/go-filecoin#3733] opened 2020-01-24 15:29 UTC
### Description
The filecoin-project/go-address module and go-filecoin's `internal/pkg/vm/address` package are identical. As go-filecoin imports more shared components, it increasingly needs to translate between module addresses provided by shared components and its own address type used internally. This effort is wasted.

### Acceptance criteria

The `internal/pkg/vm/address` package is removed and any reference to it replaced with a reference to the go-address module.

### Risks + pitfalls

This is probably a large PR, but a purely mechanical one.

**Comment by anorth** [comment] 2020-01-24 16:08
Duplicate of #3719

**Closed by anorth** 2020-01-24 16:08 UTC

**Comment by acruikshank** [comment] 2020-01-24 16:24
I searched and searched for the other issue. Don't know know why GH couldn't find it.
