### ISSUE TITLE
0.5.6 fork attack - the weight of heaviest chain should reflect the most storage provided.

### ISSUE THREAD

**Issue by taoshengshi** [filecoin-project/go-filecoin#3502] opened 2019-09-25 16:06 UTC
Describe the bug

To Reproduce
Just debug on current user devnet 0.5.6.

Screenshots
![1569426714276](https://user-images.githubusercontent.com/33315004/65617672-b9451180-dfef-11e9-8472-37688a236aac.jpg)
![1569426743713](https://user-images.githubusercontent.com/33315004/65617682-bfd38900-dfef-11e9-9ac0-dfd53b5e13de.jpg)

This could cause the user devnet be hijacked easily.
I think this is the emergency issue for the dev net security from testing purpose.

Version information
go-filecoin 0.5.6

Additional context
NA.

**Comment by ZenGround0** [comment] 2019-09-25 17:46
@taoshengshi thanks for filing this.  From your image it is not clear what the issue is.  I believe you are saying these are two different forks one with less storage than the other, but from the data all I see is that the longer chain has a higher weight which is roughly expected.

It would be very helpful to get further descriptions of the two chains.  To start with: total committed sectors on each, number of blocks/nullblocks on each, height at which they forked.

**Comment by sprwig** [comment] 2019-09-26 01:47
This problem needs to be taken seriously. When the main-net launch, if the customer can't determine whether their data is stored for a long time, they will be very anxious.

**Comment by taoshengshi** [comment] 2019-09-26 04:01
@ZenGround0 The debug level did not trigger on in advance , so I can not identify the details in logs. You could reference below summary data.

total storage power goes down after fork attack:
![powertable](https://user-images.githubusercontent.com/33315004/65656693-5be2ac00-e053-11e9-8808-bdb56afcd0ce.jpeg)

![Screen Shot 2019-09-26 at 12 00 36](https://user-images.githubusercontent.com/33315004/65657277-4b333580-e055-11e9-803b-1943af213028.png)

**Comment by ElecRoastChicken** [comment] 2019-09-26 12:45
Please solve the forking problem as soon as possible, the current network prevents miners from participating in the devnet!

**Comment by ZenGround0** [comment] 2019-09-26 18:16
Thanks for your help and expressing your concern @ElecRoastChicken @sprwig @taoshengshi.  This is certainly not taken lightly.  It needs to be clear that we absolutely will not allow major security concerns like this to exist for mainnet launch.  Please keep in mind that this is likely a protocol level concern and is potentially captured by existing work done by the research team that hasn't made it into the spec/implementation as of yet.

I'll be investigating how `t2xiji234c3zomgql5k2pr77mbvagumqopou6ncri` is going about increasing their weight to reorg to lower heights and understanding how this is impacting the power of other miners.

If you are reading this and think your operation might be responsible for this behavior feel free to explain what you are doing in the comments below.  Regardless of whether you come forward, thanks for giving us a legitimate stress test and helping us improve the network.

**Comment by ZenGround0** [comment] 2019-09-26 19:04
I'm going to draft up a gist exploring the issue in more detail.  The tl;dr of my current hypothesis is that a miner with enough power can mine their own private chain (low weight because lots of null blocks), slash everyone else's power away (because their posts aren't on the private chain) and then mine every single block (higher weight than main chain which naturally has some null blocks).

This scenario is a large motivator of the [weighting function spec's](https://github.com/filecoin-project/specs/blob/master/expected-consensus.md#chain-weighting) recent improvements.  Particularly the `P` term punishes null blocks more harshly and the `X` term rewards total storage more strongly.  go-filecoin is lagging behind the spec and does not have these terms.

We'll be validating this hypothesis and writing this up in more detail.  We'll also be evaluating upgrading the protocol to use the spec's weighting function in the near future to bring back availability to the alphanet.

**Comment by merced** [comment] 2019-09-27 01:55
While understand it takes time to implement the spec, but is there any plan for temporary solution to fix this?  This issue obviously demotivates more miners to participate the alpha net, can't imaging test net launching without wide participants in alpha net.

**Comment by ridewindx** [comment] 2019-09-27 02:26
@ZenGround0 I believe that the fork attack will be mitigated after the weighting function in specs is correctly implemented. But the formula has no mathematical proof, so we don't know how much security it has. Most of all, the convergence rate or finality of chain should be taken seriously.

**Comment by ridewindx** [comment] 2019-09-27 02:41
Normal:
A <- B <- C  <- null <- D
                C1 <- null <- null          //-- fork give up

Now:
A <- B <- C  <- null <- D
                C1 <- null <- null <- null <- D1          //-- fork win

After weighting function is implemented:
A <- B <- C  <- null <- D
                C1 <- null <- null <- null <- null <- null <- null <- D1          //-- fork still win

Would this situation happen?

**Comment by taoshengshi** [comment] 2019-09-27 04:03
> Expect:
> A <- B <- C <- null <- D
> ---------- C1 <- null <- null //-- fork give up
> 
> Now:
> A <- B <- C <- null <- D
> ---------- C1 <- null <- null <- null <- D1 //-- fork win
> 
> After weighting function is implemented:
> A <- B <- C <- null <- D
> ---------- C1 <- null <- null <- null <- null <- null <- null <- D1 //-- fork still win
> 
> Would this situation happen?

this is exactly one situation, but is good example to reveal the root cause of weight computation in [current implementation](https://github.com/filecoin-project/go-filecoin/blob/release-0.5.0/consensus/expected.go) - that is, null or n blocks(any blocks but not all) in the reorg TipSet do NOT reflect all miners's power, and therefore publish weight accumulation in parent weight - so ,this make attacker could quickly accumulate weight and at the reorg point‘s attacker 's TipSet have more proportion in weight . I guess @ZenGround0 's `Particularly the P term punishes null blocks more harshly and the X term rewards total storage more strongly.` express the same meaning.

**Comment by ridewindx** [comment] 2019-09-27 08:27
@taoshengshi It seems that you don't get the meaning of my figure above. I mean adjusting the the coefficients of the weighting function will not solve the problem completely. The security and correctness of the weighting should be formulated and proved in math.

**Comment by ridewindx** [comment] 2019-09-27 08:42
In my opinion, it would be worthwhile a try that the number of consecutive null blocks should be limited.

For example, do not allow the big power miner to generate consecutive null blocks beyond a generated real block of some small power miner:

A <- B <- C  <- null <- D    // small-power miner generated a valid block
---------- C1 <- null <- null <- null <- null <- null <- null <- D1    //-- fork should be failed
-------------------------  |
-------------------------  since this null block is beyond the valid block D

**Comment by taoshengshi** [comment] 2019-09-27 09:30
@ridewindx yeap,Now It is more clear on your illustration. There is tickets validation in function `validateMining` (consensus/expected.go:299) but no tickets validation in chain rerog . and I suggest to take more scenarios into validation at the point of reorg.

but I just agree in some what sense on coefficients adjusting of @ZenGround0 's statement, I an saying the extended meaning of `Particularly the P term punishes null blocks more harshly and the X term rewards total storage more strongly.` Actually I mean the algorithm should be changed to reflect all miners's power, that is main issue should be addressed.

```go
// Compute parent weight.
	parentW, err := ts.ParentWeight()
	if err != nil {
		return uint64(0), err
	}

	w, err := types.FixedToBig(parentW)
	if err != nil {
		return uint64(0), err
	}
	// Each block in the tipset adds ECV + ECPrm * miner_power to parent weight.
	totalBytes, err := c.PwrTableView.Total(ctx, pSt, c.bstore)
	if err != nil {
		return uint64(0), err
	}
	floatTotalBytes := new(big.Float).SetInt(totalBytes.BigInt())
	floatECV := new(big.Float).SetInt64(int64(ECV))
	floatECPrM := new(big.Float).SetInt64(int64(ECPrM))
	for _, blk := range ts.ToSlice() {
		minerBytes, err := c.PwrTableView.Miner(ctx, pSt, c.bstore, blk.Miner)
		if err != nil {
			return uint64(0), err
		}
		floatOwnBytes := new(big.Float).SetInt(minerBytes.BigInt())
		wBlk := new(big.Float)
		wBlk.Quo(floatOwnBytes, floatTotalBytes)
		wBlk.Mul(wBlk, floatECPrM) // Power addition
		wBlk.Add(wBlk, floatECV)   // Constant addition
		w.Add(w, wBlk)
	}
```
look into above code, put what I said again and attach two picture to illustrate:
that is, null or n blocks(any blocks but not all) in the reorg TipSet do NOT reflect all miners's power, and therefore publish weight accumulation in parent weight - so ,this make attacker could quickly accumulate weight (do selfish mining off the main chain) and at the reorg point‘s attacker 's TipSet have more proportion in weight .

weight increase 110 for each block(do selfish mining off the main chain):
![image](https://user-images.githubusercontent.com/33315004/65758698-18b83400-e14c-11e9-897f-e31a82eab396.png)

weight increase 48.429 for each block(main chain)
weight increase 110 for each block
![image](https://user-images.githubusercontent.com/33315004/65758813-47360f00-e14c-11e9-9824-3960437c1f79.png)

**Comment by ZenGround0** [comment] 2019-09-27 15:44
@merced getting the weight function up to spec is probably the quickest viable fix out there.  Unfortunately the team is gathering for a week of planning right now so updating the network is on pause as we don't want to hastily ship something in the next few hours that we won't have time to vet and or fix even worse bugs introduced during the fix.  I 100% agree it is a bad thing that we aren't shipping a fix sooner but this is best we can do under constraints.

@ridewindx I love that you are asking these questions.  I too am not convinced the weighting function is yet where it needs to be (this is part of the reason we didn't chose to implement it in go-filecoin as we were hoping to take in all improvements at once). I will take the time to read through and internalize your scenarios in detail and raise these concerns.  Also know that in the future bringing things like this up to @sternhenri directly in the filecoin-project/specs or filecoin-project/consensus repos is the most direct way to get us to address them.

**Comment by sternhenri** [comment] 2019-09-27 22:27
Thanks! I'm indeed at your disposal @merced, @ridewindx. 

The idea you suggest with regards to consecutive nulls is indeed one we've had (and specc'd out). In fact, the form it'll take will be penalizations based on distance from expected number of blocks (and not just null blocks which is a specific case within that). 

Feel free to check out work done [here](https://observablehq.com/d/3812cd65c054082d) on this and comment accordingly!

Henri

**Comment by anorth** [comment] 2019-10-09 14:44
We'll attempt a protocol upgrade to replace the weight function: #3540

**Closed** 2020-03-01 22:17 UTC
Labels: C-bug
