### ISSUE TITLE
Support automatic clean of storage deal piece for client or miner

### ISSUE THREAD

**Issue by ridewindx** [filecoin-project/go-filecoin#3350] opened 2019-09-04 11:19 UTC
## Description

go-filecoin currently supports importing piece at client side and fetching piece through bitswap at miner side, but these local cached pieces will never be cleaned by anyone. We should support some cleaning strategy after storage deal has been finished, such as:
- Clean single piece: `go-filecoin dag remove <pieceid>`.
- Allow automatic clean with setting TTL to the underlying badger db when insert piece, e.g., 24 hours or 30 days.

## Acceptance criteria
- The local cached pieces will not occupy disk space forever.

**Comment by anorth** [comment] 2019-09-06 01:44
Duplicate of #3062

Note that `dag remove` won't be effective - it will only remove the top node of a large DAG. Traversing the DAG is unsafe since it may delete a node used by another piece.

**Closed by anorth** 2019-09-06 01:44 UTC
Labels: C-bug
