### ISSUE TITLE
The heartbeat. The nickname cannot be synchronized to https://stats.kittyhawk.wtf/

### ISSUE THREAD

**Issue by lin6461** [filecoin-project/go-filecoin#2449] opened 2019-03-29 08:09 UTC
How do you do! Installed Filecoin, go - Filecoin config heartbeat. The nickname cannot be synchronized to https://stats.kittyhawk.wtf/, what reason is this excuse me?

**Comment by sywyn219** [comment] 2019-03-29 08:14
You describe your steps

**Comment by lin6461** [comment] 2019-03-29 08:21
> 您描述了您的步骤
Run go-filecoin config heartbeat.nickname "File" and run go-filecoin config heartbeat.beatTarget "/dns4/stats-infra.kittyhawk.wtf/tcp/8080/ipfs/QmUWmZnpZb6xFryNDe7KcJ1Af5oHy7fB9npU67sseEjR" but at https://stats.kittyhawk. Wtf / , does not display the name "File"

**Comment by sywyn219** [comment] 2019-03-29 08:26
your node reach consensus with the rest of the network. that ok!  add my QQ ^_^  email

**Comment by lin6461** [comment] 2019-03-29 08:35
> your node reach consensus with the rest of the network. that ok! add my QQ ^_^ email

What is your QQ?

**Comment by sywyn219** [comment] 2019-03-29 08:40
your email？

**Comment by lin6461** [comment] 2019-03-29 08:46
> your email？

My email 397418927@qq.com

**Comment by travisperson** [comment] 2019-03-29 17:08
I think once upon a time heartbeats could be configured while the daemon was running. However, I noticed myself with the latest release that after running the `config` command to setup the heartbeat target I had to restart the daemon for messages to be sent.

I would try to restart your daemon now that you have it configured.

**Comment by lin6461** [comment] 2019-03-29 19:18
> I think once upon a time heartbeats could be configured while the daemon was running. However, I noticed myself with the latest release that after running the `config` command to setup the heartbeat target I had to restart the daemon for messages to be sent.
> 
> I would try to restart your daemon now that you have it configured.

I installed is two days before the release of the latest version, run the daemon synchronous block prompt versions out of date, and after restart the daemon cannot display name.

**Comment by shannonwells** [comment] 2019-03-29 20:38
> I installed is two days before the release of the latest version, run the daemon synchronous block prompt versions out of date, and after restart the daemon cannot display name.

If I understand correctly, you are still running the old version you will definitely need to update to the new version first.

**Comment by shannonwells** [comment] 2019-03-29 21:01
Also @lin6461 it is probably not a good idea to post personal emails in a GitHub Issue since it is public.

**Comment by mishmosh** [comment] 2019-04-05 15:16
Closing for now, please re-open if you follow the steps above (updating to new version) and can still reproduce.

**Closed by mishmosh** 2019-04-05 15:16 UTC

**Comment by lin6461** [comment] 2019-04-07 16:18
> Also @lin6461 it is probably not a good idea to post personal emails in a GitHub Issue since it is public.

It won't send mail again, thank you for your reminder

**Comment by lin6461** [comment] 2019-04-07 16:20
> > I installed is two days before the release of the latest version, run the daemon synchronous block prompt versions out of date, and after restart the daemon cannot display name.
> 
> If I understand correctly, you are still running the old version you will definitely need to update to the new version first.

I am reinstall the latest version, is not to upgrade.
