### ISSUE TITLE
Leaky Processes from TestRetrieval

### ISSUE THREAD

**Issue by rosalinekarr** [filecoin-project/go-filecoin#2475] opened 2019-04-02 13:22 UTC
**Describe the bug**

I left my computer on sleep after leaving the office yesterday, and when I came back in this morning, it burning hot and screaming for death. I checked the process list, and it appears that `TestRetrieval` had spun up several unclosed processes when testing over the course of the day.

We need to guarantee that running tests does not leave stray processes running.

**To Reproduce**

Run `go run ./build best` a few times, Ctrl-C'ing every once in a while, then run `ps aux | grep filecoin` and see a huge list of processes that haven't stopped yet.

**Expected behavior**

No stray processes should be running when testing stops, either normally or when terminated early.

**Screenshots or Console Output**

**Desktop (please complete the following information):**
 - macOS 10.14.3
 - latest master

**Additional context**

**Comment by rkowalick** [comment] 2019-04-03 15:47
@rosalinekarr Since this is a bug and not a store, could you fill out the bug template below and put the information in the issue description?

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Run this command '...'
3. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots or Console Output**
If applicable, add logging output or screenshots.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [if applicable, e.g. chrome, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.

**Comment by rosalinekarr** [comment] 2019-04-03 20:26
@rkowalick updated

**Comment by anorth** [comment] 2019-04-12 03:59
@travisperson might this be resolved by eventual conversion to FAST?

**Comment by anorth** [comment] 2020-03-01 21:38
Ancient history

**Closed by anorth** 2020-03-01 21:38 UTC
Labels: A-tests, C-bug, C-technical-debt
